### ISSUE TITLE
API: Rename stats() to stat() and mkdirs() to mkdir() in Storage

### ISSUE THREAD

**Issue by serhiy-storchaka** [neuromation/platform-client-python#1008]
There are Python methods `os.stat()`, `pathlib.Path.stat()`, `os.mkdir()` and `pathlib.Path.mkdir()`, Posix commands `stat` and `mkdir`. There is also `os.makedirs()`, but `Storage.mkdirs()` is closer to `pathlib.Path.mkdir()` which unites `os.mkdir()` and `os.makedirs()`.

**Comment by asvetlov** [comment]
Agree. 
Good idea, I've thought about these names when worked on the storage API documentation.

**Comment by serhiy-storchaka** [comment]
Do we need to keep old aliases?

**Comment by asvetlov** [comment]
I think no.
Since we have no stable API yet we can just rename methods.
In a month we will go through deprecated alias for such case.
