### ISSUE TITLE
Add option `-d` in `neuro storage ls`

### ISSUE THREAD

**Issue by serhiy-storchaka** [neuromation/platform-client-python#1012]
I propose to add option `-d` (`--directory`) in the `neuro storage ls` command. It should work exactly like the corresponding option of the Posix command `ls`: list directories themselves, not their contents.

```
$ neuro storage ls -l storage:neuromation
-m 24 2019-08-29 12:52:45 __init__.py
dm  0 2019-08-29 11:50:41 __pycache__
dm  0 2019-08-29 11:50:42 api
dm  0 2019-08-29 11:50:44 cli
-m  8 2019-08-29 12:52:43 py.typed
dm  0 2019-08-29 11:50:43 strings
$ neuro storage ls -ld storage:neuromation
dm 0 2019-08-29 11:50:39 neuromation
```

It can be a way to check that the particular directory exists. @mariyadavydova recently requested such feature.

It can be implemented as a call of `Storage.stat()` and reusing the `ls` formatting code.

Other way to get an information about a separate file is to implement the `stat` command. The `stat` command from GNU coreutils provides more detailed information. But in our case we support only limited amount of stat information, and `ls` outputs it all.

**Comment by asvetlov** [comment]
I never used the `ls -d` option but I support the proposal if somebody needs it.
