### ISSUE TITLE
[Feature] print storage URLs in neuro ls

### ISSUE THREAD

**Issue by asvetlov** [neuromation/platform-client-python#1014]
I have many test folders in my storage.
They were created by e2e tests and not always deleted automatically.

On local filesystem I usually do something like `ls | grep test | xargs rm -rf`
`neuro rm` requires `storage:` prefix for items to delete.
I can use `sed` or `awk` but they are cumbersome a little.
Also, I need to join not `storage:` prefix only but `storage:current/dir` for `neuro ls storage:current/dir` command.

The option that prints ls content in URL form, good for machine parsing -- would be awesome.

**Comment by serhiy-storchaka** [comment]
```sh
neuro storage rm storage:test*
```

**Comment by asvetlov** [comment]
Oh, nice! I forgot that you've added globbing to `rm`.

**Comment by serhiy-storchaka** [comment]
So do you still need this feature? Are there other use cases?

I thought about adding the `storage glob` command. `neuro storage glob storage:current/dir/*` would output URIs for items in `storage:current/dir` (except that dotfiles be omitted). But I was not sure about good use case for it besides testing.

**Comment by asvetlov** [comment]
`storage glob` sounds like a really interesting idea.
I use `find` + `xargs` combination in shell pretty often. `glob` can be something like `find` but for remote storage. `xargs` can work with `glob` without any problem.

Another question is: how often people use `find` + `xargs`? I heard complains about this counter-intuitive combination. I had problems in learning this way but now apply it very often.

**Comment by serhiy-storchaka** [comment]
> `storage glob` sounds like a really interesting idea.

Time machine strikes back. I have implemented it in 19.7.17.
