### ISSUE TITLE
Rename `WHEN` column in `neuro ps`

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1020]
`WHEN` is unclear: is it when the job started or died?

**Comment by mariyadavydova** [comment]
I think that we need both, START and FINISH.

**Comment by shagren** [comment]
It's display last transition time. Pair of columns STATUS and WHEN work together
```
        if job.status == JobStatus.PENDING:
            when = job.history.created_at
        elif job.status == JobStatus.RUNNING:
            when = job.history.started_at
        else:
            when = job.history.finished_at
```

**Comment by mariyadavydova** [comment]
Oh. That's pretty contra-intuitive. I think that from the user perspective "created" and "started" are almost the same (as they should be close in ideal world). So, I would suggest having START (created or started depending on status) and FINISH (finish or "in progress" depending on status).

**Comment by shagren** [comment]
pending 1 sec g0
run at 12:00 pm
cancelled 1 day ago

**Comment by shagren** [comment]
I think we must implement first #1021,  then add new columns(created, started, finished) and maybe(not sure) change default behavior
