### ISSUE TITLE
Allow user to change columns in `neuro ps`

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1021]
together with `DESCRIPTION` and `COMMAND`, the normal output of `neuro ps` (especially `neuro ps -a`) looks frightening!

In this issue, we propose to introduce a new flag to `neuro ps` to allow user to define which columns he or she wants to see, for example: `neuro ps --columns=INOSTD` (`ID NAME OWNER STATUS TIME DESCRIPTION`).

Please note that first letters of column names must be unique.

Once this flag is introduced, we should reduce set of columns we print to `NAME_OR_ID OWNER   STATUS  TIME_CREATED  IMAGE` (please note related issue: https://github.com/neuromation/platform-client-python/issues/1020).

**Comment by asvetlov** [comment]
I like the idea but the first letters sound too cryptic.
I prefer full column names.
Minor thing, though.

**Comment by mariyadavydova** [comment]
I think with full column names this feature may become completely unusable. I can imagine adding several characters to make the output more readable, but I can't imagine printing a long line of arguments (especially being in risk of making a silly typo).

**Comment by serhiy-storchaka** [comment]
Compromise: If the arguments does not contain separators (commas or spaces or both), interpret every character as a starting character of the column. If it contains separator -- interprets separated names as names (or shortcuts) of columns.
```
neuro ps --columns=INOSTD
neuro ps --columns="ID NAME OWNER STATUS TIME DESCRIPTION"
neuro ps --columns="ID,NAME,OWNER,STATUS,TIME,DESCRIPTION"
neuro ps --columns="ID NA OW ST TI DE"
```

**Comment by mariyadavydova** [comment]
@serhiy-storchaka That's a good idea, thank you!

Also, I would better use lowercase letters (or any, as the user prefers), because switching the register is slightly annoying when you type a command in console.

**Comment by ayushkovskiy** [comment]
> Also, I would better use lowercase letters

@mariyadavydova I prefer uppercase letters as `neuro ps --columns=inostd` is much less understandable IMO. I think, column names should be uppercase also because we list them uppercase in the head of `neuro ps` ouput.

**Comment by shagren** [comment]
Let's add also something like `--format=csv`, it will help create reports or parse output

**Comment by shagren** [comment]
Why not add all available fields here? It can be something like:
* container.cpu,
* container.http
* container.volumes[0].storage_uri 
...

**Comment by ayushkovskiy** [comment]
> Let's add also something like --format=text|csv|json|yaml

I think it can  be  a separate feature for the future

**Comment by mariyadavydova** [comment]
>  I prefer uppercase letters as neuro ps --columns=inostd is much less understandable IMO. 

Looks like a matter of taste. Can we support any case? :)

> Let's add also something like --format=text|csv|json|yaml

Agree, seems to be a separate feature. I'm sure about the use-case yet. Could you please elaborate, @shagren?  

> Why not add all available fields here?

That's a good idea, but I'm afraid that there may be too many of them. Can someone share the entire list of fields here, please?

**Comment by shagren** [comment]
@mariyadavydova, `platform-metrics` now generate CSV file which used for reporting. This file like as:
```CSV
time,id,status,owner,container.image,container.resources.cpu,container.resources.memory,container.resources.gpu,container.resources.gpu_model,container.resources.shm,container.command,container.env,container.volumes,is_preemptible
2019-05-20T18:44:49.548779+00:00,job-4fd05d6d-4e15-48aa-a190-26cfb7e143be,succeeded,shagren,"{'name': 'alpine', 'tag': 'latest', 'owner': None, 'registry': None}",0.016666666666666666,,,,0.16666666666666666,sleep 15m,{},[],0.16666666666666666
2019-05-20T18:52:50.762815+00:00,job-17192742-afba-473e-88bd-4b99d3ac6c76,succeeded,shagren,"{'name': 'alpine', 'tag': 'latest', 'owner': None, 'registry': None}",0.016666666666666666,,,,0.16666666666666666,sleep 15m,{},[],0.16666666666666666
...
```

Raw payload(for fields):
```JSON
{
  "id": "job-6f7b88ad-e8ec-4199-aa63-20dff8158cb5",
  "owner": "shagren",
  "cluster_name": "default",
  "status": "succeeded",
  "history": {
    "status": "succeeded",
    "reason": null,
    "description": null,
    "created_at": "2019-05-17T11:59:22.768782+00:00",
    "started_at": "2019-05-17T11:59:35.389683+00:00",
    "finished_at": "2019-05-17T11:59:35.389683+00:00"
  },
  "container": {
    "image": "ufoym/deepo:all-jupyter",
    "env": {},
    "volumes": [],
    "resources": {
      "cpu": 7,
      "memory_mb": 30720,
      "gpu": 1,
      "gpu_model": "nvidia-tesla-k80",
      "shm": true
    },
    "http": {
      "port": 80,
      "health_check_path": "/",
      "requires_auth": false
    }
  },
  "ssh_server": "ssh://nobody@ssh-auth-dev.neu.ro:22",
  "ssh_auth_server": "ssh://nobody@ssh-auth-dev.neu.ro:22",
  "is_preemptible": true,
  "name": "jupyter",
  "http_url": "https://job-6f7b88ad-e8ec-4199-aa63-20dff8158cb5.jobs-dev.neu.ro",
  "http_url_named": "https://jupyter--shagren.jobs-dev.neu.ro",
  "internal_hostname": "job-6f7b88ad-e8ec-4199-aa63-20dff8158cb5.default"
}
```

**Comment by asvetlov** [comment]
AFAIK `platform-metrics` uses API, not CLI.
It can generate a report in any format on its own

**Comment by shagren** [comment]
Added separate issue #1050, for machine-readable output format supports

**Comment by mariyadavydova** [comment]
@asvetlov I'm very sorry for the late response. I agreed with you internally and forgot to write a reply.

Let's postpone merging this feature for a little while. The current output of `ps` is not ideal, but it is pretty useful as is.

**Comment by asvetlov** [comment]
No problem. I assumed that silence is for agreement :)

**Comment by ayushkovskiy** [comment]
Closed by https://github.com/neuromation/platform-client-python/pull/1288/ and later PRs
