### ISSUE TITLE
Should rise an exception on ambiguous job-name

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1024]
when job is addressed via URI (`neuro status job://owner/job-name`), this URI incorporates owner's name, so multiple running/pending jobs is impossible case. However, if the job is addressed via bare job name (`neuro status job-name`), this job-name may refer to a self user's job or other user's job shared with the first user. Thus job-name is ambiguous, we should raise an exception. Currently, we resolve it as the calling user (see https://github.com/neuromation/platform-client-python/issues/988, https://github.com/neuromation/platform-client-python/pull/999/).

**Comment by ayushkovskiy** [comment]
and also, if the the bare job name is used (not uri), we should not resolve apply filter by owner when resolving

**Comment by serhiy-storchaka** [comment]
I think the calling user should have a preference, and no exception should be raised.

Otherwise I could sabotage your work by granting jobs with names that match your job names. It will make using a job name for addressing a job non-guaranteed.

**Comment by ayushkovskiy** [comment]
> Otherwise I could sabotage your work by granting jobs

Good point! thank you @serhiy-storchaka , I agree that CLI should include `owner=myself` when resolving both `job-name` and `job:job-name` to job-ID. I'd like to close this issue.
