### ISSUE TITLE
make init is not compatible with git worktree

### ISSUE THREAD

**Issue by serhiy-storchaka** [neuromation/platform-client-python#1031]
When create a worktree using the `git worktree` command `make init` will fail in it because `.git` is not a directory but a file.
```
cp .hooks/* .git/hooks
cp: failed to access '.git/hooks': Not a directory
Makefile:71: recipe for target 'init' failed
make: *** [init] Error 1
```
It is not critical, and the error can be ignored.

**Comment by asvetlov** [comment]
Skip copy if `.git` is not a dir?

**Comment by asvetlov** [comment]
Hooks are dropped by #1089 1184
