### ISSUE TITLE
Return code is 0 when job not found

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1045]
```
$ n kill keks
Cannot kill job keks: {"error": "no such job keks"}
$ echo $?
0
```

**Comment by ayushkovskiy** [comment]
Please note that if we fix this, the template will be broken: 
https://github.com/neuromation/platform-template/blob/36740c0b76c226347af053485b35ef7014cc562b/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L33
Here make command will break if any of commands returned non-zero

**Comment by asvetlov** [comment]
Please decide what to do; keep the fix in sync with the cookiecutter template

**Comment by serhiy-storchaka** [comment]
It currently returns 1. The error output also was improved.
```
$ neuro kill keks; echo $?
Cannot kill job keks: no such job keks
1
```
But different commands produce different error output and error codes.
```
$ neuro status keks; echo $?
ERROR: Illegal argument(s) (no such job keks)
65
$ neuro top keks; echo $?
ERROR: Job not found. Job Id = keks
127
```

**Comment by serhiy-storchaka** [comment]
I close this issue and open the new one: #1626.
