### ISSUE TITLE
Machine-readable output for ls/ps/images

### ISSUE THREAD

**Issue by shagren** [neuromation/platform-client-python#1050]
Let's add ability for rendering listings in machine-readable formats: csv, json, yaml.
It can be used for 
* reporting, i.e. cluster daily usage 
* scripting, i.e. for multi-node job orchestrating
* complex client-side filtering with `jq`

cc @mariyadavydova

**Comment by asvetlov** [comment]
We have an API that can be used for all these tasks easily.

I suggest postponing the issue until we have at least one the real use case.
