### ISSUE TITLE
Clarify memory size in 'neuro config show'

### ISSUE THREAD

**Issue by asvetlov** [neuromation/platform-client-python#1063]
Currently, the output is
```
Name         #CPU    Memory   Preemptible   GPU
cpu-micro     0.1       100        ✖︎
cpu-small       1      4096        ✖︎
cpu-large       3     12288        ✖︎
gpu-small       7     30720        ✖︎        1 x nvidia-tesla-k80
gpu-large       7     30720        ✖︎        1 x nvidia-tesla-k80
```
Memory column is not obvious. I know that the size is in megabytes but `4096` looks obscure for a newbie. Humanized version, e.g. `4GB` looks better.

**Comment by asvetlov** [comment]
@mariyadavydova I appreciate your opinion here as well as @astaff smile :)

**Comment by serhiy-storchaka** [comment]
Agree. The `--memory` option requires a value with a suffix, like `1G` or `20M`, so it would be better to output it in the same format.

**Comment by mariyadavydova** [comment]
Agree. 4GB makes much more sense that 4096 of "what memory unit these guys use?.."
