### ISSUE TITLE
Add the option `neuro port-forward --forever`

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1088]
use-case 1: the connection opened by `neuro port-forward` has failed,

use-case 2: the user closes the laptop lid and returns back to work in 5 minutes (the job remains running).

In both cases, the user has to find the terminal where the command was executed and re-run it, otherwise, remote debugging via PyCharm won't work. Instead, we could re-run `neuro port-forward` automatically.

**Comment by shagren** [comment]
What behavior will be if system restarted?

**Comment by dalazx** [comment]
`--forever` might seem misleading. it rather reconnects/retries.

**Comment by ayushkovskiy** [comment]
> What behavior will be if system restarted?

I think, if `neuro port-forward` finishes after the computer restart it's totally fine (because we didn't ask anyone to put such a system-wide daemon). However, we might need a daemon to catch the events "laptop lid closed", "laptop hibernated"

**Comment by shagren** [comment]
agreed with @dalazx, `--reconnect` will be better

**Comment by serhiy-storchaka** [comment]
Why not reconnect by default?

**Comment by ayushkovskiy** [comment]
I agree with doing `neuro port-forward --reconnect` by default, so to have something like `neuro port-forward --once`

**Comment by asvetlov** [comment]
done as a part of #1555
