### ISSUE TITLE
Kill the active job on KeyboardInterrupt

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1089]
when the user aborts the job while it is Pending (for example, while the resources are being allocated), we should send `neuro kill` to that job-ID so that the next attempt to run the same job with the same name will not fail. 

The argument here is simple: since the job is still Pending, it does not compute anything useful for the user, therefore are allowed to kill it.

**Comment by dalazx** [comment]
I agree that intuitively one may presume that the job is killed on ^C, but I don't thing we should implicitly kill it. instead, considering that `neuro` is used in interactive mode, we could simply ask the user whether the job should be killed. or, rather, we could ask whether the existing job with the same name should be replaced.

**Comment by ayushkovskiy** [comment]
I agree. And let's do this not only to pending jobs, but also to running jobs!

**Comment by asvetlov** [comment]
@ayushkovskiy do you want to be a champion?

**Comment by ayushkovskiy** [comment]
I wish! but I'm currently overloaded with other work :pensive:

**Comment by asvetlov** [comment]
The same is true for any person from our team I guess.

**Comment by asvetlov** [comment]
done
