### ISSUE TITLE
Error while killing a bunch of jobs

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1122]
Case: `neuro kill job-A job-B job-C`. Suppose, my user has no permissions on `job-B`.

Expected behaviour:
```
job-A
ERROR: Not enough permissions ({"missing": [{"uri": "job-B", "action": "write"}]})
job-C
```
i.e., `neuro` failed to kill `job-B`, however it continued to kill other jobs (`job-C`).

Actual behaviour:

```
job-A
ERROR: Not enough permissions ({"missing": [{"uri": "job-B", "action": "write"}]})
```
i.e., `job-C` was not killed.

**Comment by asvetlov** [comment]
Low priority I guess

**Comment by serhiy-storchaka** [comment]
It looks similar to #1044.
