### ISSUE TITLE
Introduce `neuro config quota show`

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#1141]
We need to be able to communicate to our users about their quota situation.

`neuro config quota show` should render the current jobs run-time consumed and quota for the current user's cluster.

The information should be retrieved using https://github.com/neuromation/platform-api/issues/901.

Optionally, the command should output a suggestion for topping up the quota.

cc @asvetlov @mariyadavydova

**Comment by asvetlov** [comment]
It can live in `config` group for now.
When we implement organizations we can reconsider the command position, moving with the deprecation of previous notation is not a big deal.

**Comment by ayushkovskiy** [comment]
Guys are we OK with this output format?
```
GPU left: 167h 23m 32s (quota: 200h 00m 00s)
CPU left:  00h 00m 32s (quota: 1000h 00m 00s)
```

**Comment by mariyadavydova** [comment]
@ayushkovskiy 👍

**Comment by ayushkovskiy** [comment]
Huh, we don't provide seconds for quota.. So the formatting will look like:
```
GPU left: 167h 23m (quota: 200h 00m)
CPU left:  00h 00m (quota: 1000h 00m)
```
@mariyadavydova HDYT wouldn't it look weird without seconds?

**Comment by mariyadavydova** [comment]
@ayushkovskiy Well, that's OK. I don't think that seconds really matter here, when we speak about 100h quotas.

**Comment by ayushkovskiy** [comment]
How do we format lack of quota? `(quota: NaN)` or `(quota: None)` or `(quota: ∞)`?

**Comment by mariyadavydova** [comment]
The last one is the most accurate, I guess.

**Comment by ayushkovskiy** [comment]
the sign looks too tiny

**Comment by mariyadavydova** [comment]
We may simply say `(quota: infinite)`. I don't think that this question is very important ATM, though, because those who have no quota (i.e. non-free-tier folks) will hardly ever execute this command.

**Comment by asvetlov** [comment]
+1 for 'infinity'. Not all terminals support Unicode symbols.

**Comment by ayushkovskiy** [comment]
if `quota == infinity`, `left` is also `infinity`. Let's stick to this formatting:
```
GPU spent: 167h 23m (quota: 170h 23m, left: 03h 00m)
CPU spent:  00h 00m  (quota: infinity)
```
