### ISSUE TITLE
Introduce `neuro config add-quota`

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#1142]
A follow-up for https://github.com/neuromation/platform-client-python/issues/1141.

The proposed `neuro config quota add` command should:
1. give directions for topping-up the quota using a 3rd-party payment service;
2. optionally open a web browser and fill all the required information for the user and their cluster.

**Comment by ayushkovskiy** [comment]
Since we have decided to use `neuro config show-quota` syntax instead of `neuro config quota show` (see https://github.com/neuromation/platform-client-python/pull/1156#discussion_r344114834), which syntax is acceptable for `quota add` command? Are we OK with `neuro config add-quota`?

**Comment by serhiy-storchaka** [comment]
I propose `neuro config add-quota`. It will likely be changed when we add more similar commands.

**Comment by asvetlov** [comment]
@anayden is it done?

**Comment by anayden** [comment]
`neuro config add-quota` is not ready yet, because quota top-up feature isn't released on the website.

**Comment by asvetlov** [comment]
Fixed by #1275
