### ISSUE TITLE
Rename pypi package from neuromation to neuro

### ISSUE THREAD

**Issue by astaff** [neuromation/platform-client-python#1147]
... so one can install it us as `pip install -U neuro`.

Other parts of package structure can remain neuromation (if applicable).

**Comment by asvetlov** [comment]
> Other parts of package structure can remain neuromation

A sign of an ansient package that cannot rename itself for legacy reasons :)

**Comment by astaff** [comment]
I hear you. Let's do it right and rename everything properly.

**Comment by asvetlov** [comment]
`neuro` already exists on PyPI
