### ISSUE TITLE
Allow `neuro ls` on files (as by Posix)

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1148]
```
$ n ls storage:path/script.py
ERROR: cannot access storage://ayushkovskiy/path/script.py: {"error": "Not a directory"}
$ n ls storage:path/
script.py script_2.py
```

However bash allows:
```
[ay@archlinux ~]$ ls path/a
path/a
[ay@archlinux ~]$ ls path
a

```

**Comment by asvetlov** [comment]
Super minor I guess

**Comment by yartem** [comment]
Let's increase the severity of this issue: this is very useful to check if the file is present on Storage or not and when the base directory of the file contains thousands of other files (thus, `neuro ls {base_directory}` takes super-long time).

**Comment by serhiy-storchaka** [comment]
You can use `ls -d` for this.

**Comment by yartem** [comment]
@serhiy-storchaka , thank you, `ls -d` indeed works, however it's not obvious for me as a user, why
