### ISSUE TITLE
Preserve overall Pending time of the job

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1154]
```$ neuro run ...
...
Shortcuts:
  neuro status inga-dev-eval-manuals  # check job status
  neuro logs inga-dev-eval-manuals    # monitor job stdout
  neuro top inga-dev-eval-manuals     # display real-time job telemetry
  neuro kill inga-dev-eval-manuals    # kill job
Status: pending Initializing ◤ [921.1 sec]
```
If the job stays long in the `initializing` state, the user might be frustrated if we hide the final time of the job startup. I think, we should keep the client as much transparent as possible.

**Comment by mariyadavydova** [comment]
Agree, I would prefer to see this information. 
For me, it is better to see that the job was initialized in 921 seconds, rather than "It took so long that I went out for lunch, drank a cup of coffee, came back and found out that it is finally initialized'.

**Comment by asvetlov** [comment]
People, I don't follow what problem do you want to solve and what is the proposal

**Comment by yartem** [comment]
The problem purely psychological: neuro CLI wipes out the elapsed time of the job startup time, which can sound like the CLI tending to be more obscure, to hide this essential information. I think, the latest number, that was printed during the every-second check, should be kept.

**Comment by asvetlov** [comment]
Up to you. Please feel free to make a PR
