### ISSUE TITLE
Files jump while `neuro cp -r`

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1163]
See https://asciinema.org/a/xpl1M3ObqLqOJzsBBhOg2Dex8

I have received multiple complains of the users who try `neuro cp -r` for the first time: for them, file names blinking on the screen looks like a bug. Perhaps, it's better not to re-write lines in terminal, but just print them on new line (as, for exapmle, zip does: https://asciinema.org/a/ypszHC9MvRXYaXCqO7I0l02vc)

**Comment by serhiy-storchaka** [comment]
zip uses a single thread. `neuro cp -r` copies multiple files simultaneously.

**Comment by asvetlov** [comment]
I would say that the idea of neuro CLI is to avoid the very long output.
That's why we print only last N items in the copy progress, limit the number of lines in job start indicator and use pagers in storage/jobs/whatever listings.
This behavior is the default if the terminal is interactive (TTY mode is on).

**Comment by ayushkovskiy** [comment]
The fact is that blinking terminal scares users. Thankfully the high speed of `neuro cp`, the names of smaller files re-appear on the screen very fastly, which confuse many users (again, I have received multiple feedbacks on this problem).

Maybe an alternative solution would print only names of those files whose size will not cause blinking (say, whose size is bigger than 512B?)

**Comment by asvetlov** [comment]
The PR is welcome, sure.
The minor thing I guess.

**Comment by serhiy-storchaka** [comment]
I agree that this issue is not completely resolved. Currently I am working on my other idea.
