### ISSUE TITLE
Add `neuro config select-cluster [cluster-name]`

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#1178]
from https://docs.google.com/document/d/1A9STpF-9vlaVAaCisCqo-o7NU-Kikc9aFsEHOwImuKY/edit#

**neuro config select-cluster [cluster-name]**
Pulls the ready-to-use clusters available to the user;
Outputs the list of clusters and requests the user to select one, if the cluster name is not provided;
Looks up a cluster configuration by the selected cluster name;
Saves the selected cluster configuration to the config file.

Once https://github.com/neuromation/platform-api/issues/966 is ready, we could reuse some existing code to request `GET /api/v1/config`, parse the `clusters` key in the response payload and, depending on the passed `cluster_name` and TTY, either prompt or just lookup and rewrite `.nmrc`.

**Comment by asvetlov** [comment]
Fixed by #1217
