### ISSUE TITLE
neuromation package url (homepage)

### ISSUE THREAD

**Issue by shagren** [neuromation/platform-client-python#1185]
At this moment it points to https://neuromation.io
Let's change it to this repo

**Comment by dalazx** [comment]
or `https://neu.ro`?

**Comment by asvetlov** [comment]
A link to github is better if we modify README.
I suggest dropping autogenerated endless CLI documentation but replace it with 
1. a few words about the package
2. Link to neu.ro
3. Link to CLI docs hosted on neu.ro
4. Link to API docs hosted on readthedocs
5. Link to "Getting started" with installation instructions and other things

Later we can add more information, e.g. instructions for new contributors etc.

/cc @mariyadavydova

**Comment by mariyadavydova** [comment]
Totally agree. Generated CLI documentation in this repo README seems useless to me.

**Comment by asvetlov** [comment]
done
