### ISSUE TITLE
Extend output of `neuro run` with a reminder to kill GPU job

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1191]
`-s gpu-small` looks very similar to `-s cpu-small`, so when I use the platform, I always spend extra attention on whether I should be extra careful or not to kill the job.

How about we print a warning for jobs that use GPU:

```
Job ID: job-1d9ad24c-f960-4e8b-bb59-60573c87e141 Status: pending
Name: jupyter-ml-workflow-example
Http URL: https://jupyter-ml-workflow-example--artemyushkovskiy.jobs.neuro-ai-public.org.neu.ro
Shortcuts:
  neuro status jupyter-ml-workflow-example     # check job status
  neuro logs jupyter-ml-workflow-example       # monitor job stdout
  neuro top jupyter-ml-workflow-example        # display real-time job telemetry
  neuro exec jupyter-ml-workflow-example bash  # execute bash shell to the job
  neuro kill jupyter-ml-workflow-example       # kill job
Status: pending Creating
Status: pending Scheduling
Status: pending ContainerCreating
Status: running
Warning: this job uses 2x GPU, please don't forget to kill this job when you don't need it.
...
```

I've seen this warning in [fastai docs](https://course.fast.ai/start_gcp.html): `and don’t forget to stop your instance`

I'm still not sure if we need this feature or not, so you are welcome share your opinion here!

**Comment by ayushkovskiy** [comment]
JFYI: another reminder in the beginning of the docs: https://github.com/cs231n/gcloud/#big-reminder-make-sure-you-stop-your-instances

So the teachers always remind the students to kill their jobs
