### ISSUE TITLE
Parse multiple last arguments of `neuro run` as the command

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1198]
I was surprised when discovered that the job's command with arguments must always be quoted:
```
$ n run -s cpu-small -n test ubuntu "bash -c 'echo 1 && echo 2 && echo 3'"
...
1
2
3
$ n run -s cpu-small -n test ubuntu bash -c 'echo 1 && echo 2 && echo 3'  # no quotation surrounding command => job succeeded, but no output

$
```
Question:
If only `bash` is interpreted as the job's command and all other arguments are discarded, why then the job gets `succeeded`?

Proposal:
In any case, let's allow the second case.

**Comment by asvetlov** [comment]
Closing because of #927

P.S.
@ayushkovskiy perhaps we have a different understanding of the bug tracker role.
Personally, I don't think that this is the right place for dumping all random thoughts about the platform.
Please, find another tool for using as a personal notebook.

**Comment by ayushkovskiy** [comment]
No IMO this issue was in its right place, though it was a duplicate of issue https://github.com/neuromation/platform-client-python/issues/1229 which was closed in https://github.com/neuromation/platform-client-python/pull/1237.
