### ISSUE TITLE
tqdm doesn't work in neuro logs

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1199]
ML guys rely on tqdm output extensively. Perhaps the problem is that neuro logs are written in non-pseudo-tty mode.

**Comment by asvetlov** [comment]
It's because tqdm doesn't support async iterators: https://github.com/tqdm/tqdm/pull/772 etc.

Not the problem of this project.

**Comment by ayushkovskiy** [comment]
@asvetlov I don't think The issue should be closed as the problem is not resolved. Let's reopen this issue to find a workaround?

**Comment by ayushkovskiy** [comment]
wait: ML engineers' code is synchronous. The problem is with rendering. We need to experiment with standalone utility `tqdm` printing to a job's output.

**Comment by ayushkovskiy** [comment]
Re-open after receiving yet another complain from @atselousov . Please don't close this issue until we get `tqdm`'s output visible from `neuro logs` output during the training (it's visible only at the final step).

**Comment by asvetlov** [comment]
I don't follow.
Does `tqdm` work when the output is redirected to a file?
The job is executed in non-TTY mode unless `job exec`  is used.
I wonder what do you expect from non-TTY?

To be clear: TTY means a connected terminal, this condition is not true for `job run`.  We display *job logs* in output, it makes a difference while sometimes may look like interactive session.

**Comment by ayushkovskiy** [comment]
Minimal example that should work:
```
$ neuro run -s cpu-small image:neuromation/base-tqdm 'python -c "from tqdm import tqdm; from time import sleep; [sleep(0.01) for i in tqdm(range(10000))]"'
...
```
While the job is running, it should produce the bar to the output of `neuro logs`, however it only prints the final line:
```
100%|██████████| 10/10 [00:00<00:00, 94.98it/s]
```

**Comment by ayushkovskiy** [comment]
At least I expect what's happening with `neuro`'s output during job being pending in non-TTY mode:
```
[1AStatus: [33mpending[0m [1mCreating[0m ◢ [0.6 sec][0K
[1AStatus: [33mpending[0m [1mCreating[0m ◣ [0.9 sec][0K
[1AStatus: [33mpending[0m [1mCreating[0m[0K
Status: [33mpending[0m [1mScheduling[0m
[1AStatus: [33mpending[0m [1mScheduling[0m ◤ [1.5 sec][0K
```
At most, if possible, I expect the same bar as is printed in TTY mode.

**Comment by ayushkovskiy** [comment]
Also, sometimes , succeeded jobs don't leave any output (see, for example `job-3d68755b-4d12-48f2-941b-afbf8467af2d` on `neuro-ai-public` that was submitted with the same command). But that's likely to be a server-side bug

**Comment by ayushkovskiy** [comment]
we can run `tmux` via `neuro rum`, and then connect to it via `neuro exec`.

For me TODO: describe this in details

**Comment by ayushkovskiy** [comment]
it seems that to make tqdm work in neuro logs, we need to disable buffering on docker side, because locally stream reading works just fine:
```
$ python -c "from tqdm import tqdm; import time; [time.sleep(0.1) for x in tqdm(range(100))]" 2> file.txt & 
[1] 1244336
$ tail -f file.txt 
 80%|████████  | 80/100 [00:08<00:02,  9.95it/s]^C
```

**Comment by ayushkovskiy** [comment]
Maybe tweaking batch size or buffering will help?
1. https://github.com/neuromation/platform-monitoring/blob/214420bc88044c14754a6d2b175abb6e3704cc98/platform_monitoring/api.py#L114

2. buffering of the logs on docker/kubernetes side?

**Comment by astaff** [comment]
if i `print` inside the loop it outputs tqdm progress as well

```
from tqdm import tqdm
from time import sleep

for i in tqdm(range(10000)):
	print(f"{i}")
	sleep(0.5)
```

**Comment by astaff** [comment]
As @asvetlov correctly stated, we are capturing stdout and displaying it in `neuro logs` line by line. `tqdm` uses `\r` to display a nice progress bar in TTY, not `\n'. Here is a related issue: https://github.com/tqdm/tqdm/issues/750

@ayushkovskiy to make your example more accurate, you should have used `cat`, not `tail -f`

**Comment by astaff** [comment]
https://github.com/neuromation/platform-monitoring/blob/master/platform_monitoring/logs.py#L57 is likely awaiting `\n`. I don't know if underlying machinery of k8s allows anything else

**Comment by dalazx** [comment]
did some preliminary research. got some insights and an idea how to improve things with a relatively small fix, but it won't be ideal. there's even a better way. I'll share soon.

**Comment by ayushkovskiy** [comment]
@dalazx thank you for handling this problem! However, it seems that patching `platform-monitoring` is not enough, my test still does not work:
```
neuro run -s cpu-small image:python-tqdm 'python -c "from tqdm import tqdm; from time import sleep; [sleep(0.01) for i in tqdm(range(10000))]"'
```
:pensive:

**Comment by dalazx** [comment]
```
neuro run -s cpu-small --entrypoint python tqdm/tqdm -c "import time, tqdm;[time.sleep(0.01) for _ in tqdm.tqdm(range(int(1e6)))]"
Job ID: job-6bacc746-bd4c-4b9d-b2c5-21b669b74c9b Status: pending
Http URL: https://job-6bacc746-bd4c-4b9d-b2c5-21b669b74c9b.jobs-dev.neu.ro
Shortcuts:
  neuro status job-6bacc746-bd4c-4b9d-b2c5-21b669b74c9b     # check job status
  neuro logs job-6bacc746-bd4c-4b9d-b2c5-21b669b74c9b       # monitor job stdout
  neuro top job-6bacc746-bd4c-4b9d-b2c5-21b669b74c9b        # display real-time job telemetry
  neuro exec job-6bacc746-bd4c-4b9d-b2c5-21b669b74c9b bash  # execute bash shell to the job
  neuro kill job-6bacc746-bd4c-4b9d-b2c5-21b669b74c9b       # kill job
Status: pending Creating
Status: pending Scheduling
Status: pending ContainerCreating
Status: running
Terminal is attached to the remote job, so you receive the job's output.
Use 'Ctrl-C' to detach (it will NOT terminate the job), or restart the
job with `--detach` option.                
  2%|▏         | 17660/1000000 [02:58<2:45:37, 98.85it/s]
```

but there's still a delay though and there's nothing we can do with it.
by default `docker` flushes long lines to the log files when they reach the length of **16k**. it is the case for `Docker for Mac` and `minikube` at least.
I am observing a slightly higher threshold on GCP: **110k**. they might have as well built `docker` themselves with the changed value.

I'll try to investigate of it's possible to change that value somehow.

**Comment by ayushkovskiy** [comment]
Oh yes I see now. But unfortunately the problem remains: tqdm is still useless: the thresholds seem to be too big, so the tqdm output fiirst pends for a long time, and then in ~1-2 min outputes all at once. Can we reduce the thresholds?
