### ISSUE TITLE
Not setting up env variable during --volume=HOME

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1202]
We print that `Mountpoint will be available in via variable NEUROMATION_HOME`, but don't actually set the variable:

https://github.com/neuromation/platform-client-python/blob/6365e51355158e2d5d391895ee44630bfcf6ddb7/neuromation/cli/job.py#L974-L994

Note: the command is already deprecated, maybe it's time to drop it. Maybe it's time to fix it.

**Comment by asvetlov** [comment]
I vote on the dropping.
