### ISSUE TITLE
Port-forward does not check if the job is alive (neither on command start, nor while working)

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1216]
I think `neuro port-forward` should be aborted once the job is terminated, especially when the flag `--reconnect` is implemented.

Though I'm not sure how to implement this correctly avoiding polling the API questioning if the job is alive.

**Comment by ayushkovskiy** [comment]
Also, `neuro port-forward job-name` succeeds even if the job `job-name` is terminated.

**Comment by asvetlov** [comment]
It is the server bug, isn't it?

**Comment by ayushkovskiy** [comment]
oh, right! I'll move the issue there.

**Comment by ayushkovskiy** [comment]
https://github.com/neuromation/platform-api/issues/1030
