### ISSUE TITLE
Add `neuro admin generate-cluster-config`

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#1227]
This is an interactive command that asks a user a series of questions and, as a result, writes a combined yaml file under the specified path. If the path was omitted, the default value should be used. the resulting path should be commentated regardless.

the questions should be based on the response from 
```
curl -H "Content-Type: application/json" \
     https://dev.neu.ro/api/v1/cloud_providers
```
 https://github.com/neuromation/platform-config#cloud-provider-configuration-options

the resulting file should have the structure that is expected as a payload to the clusters cloud providers route: https://github.com/neuromation/platform-config#configuring-cloud-provider

the node pool configuration and the storage configuration should be generated based on the defaults in the following doc.

see https://docs.google.com/document/d/1muPCUJzJat6ciCfOe9QbSug6skfYEF1XtUarpiUGu4o/edit# for more details.

**Comment by zubenkoivan** [comment]
Default configuration of GCP cloud provider:
```
{
    "type": "gcp",
    "location_type": "multi_zonal",
    "region": "us-central1",
    "zones": [
        "us-central1-a",
        "us-central1-c"
    ],
    "project": "", // your project name
    "credentials": {}, // your credentials
    "node_pools": [
        {
            "id": "n1_highmem_8",
            "min_size": 1,
            "max_size": 4
        },
        {
            "id": "n1_highmem_8_1x_nvidia_tesla_k80",
            "min_size": 1,
            "max_size": 4
        }
    ],
    "storage": {
        "id": "standard",
        "capacity_tb": 1
    }
}
```

**Comment by zubenkoivan** [comment]
Default configuration of AWS cloud provider:
```
{
    "type": "aws",
    "region": "us-east-1",
    "zones": [
        "us-east-1a",
        "us-east-1b"
    ],
    "credentials": {
        "access_key_id": "your_access_key_id",
        "secret_access_key": "your_secret_access_key"
    },
    "node_pools": [
        {
            "id": "m5_2xlarge",
            "min_size": 1,
            "max_size": 4
        },
        {
            "id": "p2_xlarge_1x_nvidia_tesla_k80",
            "min_size": 1,
            "max_size": 4
        }
    ],
    "storage": {
        "id": "generalpurpose_bursting"
    }
}
```

**Comment by mariyadavydova** [comment]
@zubenkoivan I have some questions regarding these configs: 
1. Can we add V100 in the default cluster config as well? With min_size 0 and max_size 1?
2. Does min_size 1 for K80 mean that there is always an idle k80 node? I mean, I understand that my assumption is probably wrong, but how do we indicate the fact that we always want an idle k80 node available?
3. In AWS, is "generalpurpose_bursting" the same as standard storage in GCP? Also, is it paid on demand in AWS?

**Comment by zubenkoivan** [comment]
@mariyadavydova 
1. Will update
2. min_size means that there always will be at least 1 node in each zone, but it is not idle, it can have jobs.
3. Yes, they are equivalent, the only difference that it does not have preallocated storage, we pay only for the amount of data we upload.
