### ISSUE TITLE
Make it easier to determine new project directory after neuro project init

### ISSUE THREAD

**Issue by astaff** [neuromation/platform-client-python#1230]
Every time I create a new project, my immediate next action is to `cd` into project directory and either open it in my editor or run `make setup`. Things get more complicated if project slug is different from actual name.

My current workaround is to copy-paste slug suggested from `neuro project init` prompt which adds a manual step and complicates writing tutorials.

I see a few possible solutions:

1. Automatically change into project directory, then the name can be obtained using `${PWD##*/}`. Drawback is some users might not expect this side effect from running the cli. `git init` and [Create React App](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app) don't `cd`.

2. Take directory name as an optional argument in `neuro project init`: check if it's a valid slug and default slug and long name to it. `git init` does the same.

I am favoring no. 2 as it can also make `neuro project init` ask less questions. I am using [React scaffolding](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app) as an example.

**Comment by asvetlov** [comment]
`neuro` cannot change the current directory of the parent process, the shell in your example.
Option 1) is impossible.

**Comment by astaff** [comment]
Thanks, @asvetlov . Looks like no. 2 it is, unless there are other suggestions
