### ISSUE TITLE
Do proper re-login of migrated users

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1231]
Use-case: after the migration to another cluster has been completed, the user didn't re-login (as we asked them in the e-mail -- they usually don't read e-mails). As a result, the user tries to work the the older cluster. 

Solution: Potentially we could not only refresh an expired token,  but also sync the config.

See in thread: https://neuromation.slack.com/archives/CE76BT03G/p1575642931030700

**Comment by asvetlov** [comment]
All active users are migrated already
