### ISSUE TITLE
Introduce `neuro admin set-user-quota`

### ISSUE THREAD

**Issue by anayden** [neuromation/platform-client-python#1255]
The proposed `neuro admin set-user-quota USERNAME --non-gpu=100 --gpu=200` should set non-GPU quota value to 100 minutes and GPU quota value to 200 minutes respectively for user USERNAME.

**Comment by dalazx** [comment]
as quotas are now per cluster, we need to be able to specify a cluster name in the command arguments. also we might want consider adding an ability to increase a user's quota rather than rewrite its previous values.

**Comment by anayden** [comment]
`neuro admin set-user-quota --cluster=CLUSTER --user=USER --non-gpu=100 --gpu=200`?

`neuro admin add-user-quota --cluster=CLUSTER --user=USER --non-gpu=50`?

cc @dalazx

**Comment by dalazx** [comment]
yeah, or something similar but more consistent with the existing cluster user management commands where the cluster and user names are arguments rather than options.

cc @asvetlov @tvoinarovskyi @mariyadavydova

**Comment by serhiy-storchaka** [comment]
`neuro admin add-user-quota CLUSTER USER --non-gpu=100h --gpu=200m`

**Comment by serhiy-storchaka** [comment]
For quota we should use suffixes `h` (hours) or `m` (minutes). Perhaps also support fractional quantities (`2.5h`).

**Comment by tvoinarovskyi** [comment]
@dalazx Serhiy's proposal seems very sane to me, it matches with our API's. Probably 1 more thing to note, the API right now has "role" not optional and you would have to GET and only then PUT for both commands. It's not a big problem, as for add-user-quota you would do that anyway.

**Comment by dalazx** [comment]
@tvoinarovskyi at least for now, yes. later we could introduce `PATCH /quota` or smth similar.
