### ISSUE TITLE
Fix broken e2e test on Windows

### ISSUE THREAD

**Issue by asvetlov** [neuromation/platform-client-python#1258]
Was introduced by #1254
@anayden, please fix ASAP

**Comment by serhiy-storchaka** [comment]
Could you please show a traceback or a link to test logs?

**Comment by anayden** [comment]
https://dev.azure.com/neuromation/platform-client-python/_build/results?buildId=1732&view=logs&j=45f448c1-7a4d-56c6-196a-86747a444dcb&t=001c8d1e-0187-5d04-7be3-da6113fdc37c

**Comment by serhiy-storchaka** [comment]
The `cookiecutter-neuro-project` project contains directory `{{cookiecutter.project_slug}}`. Is it valid filename on Windows?

**Comment by anayden** [comment]
This is a standard directory for cookiecutter projects, so I would be surprised if it wasn't compatible with windows.

In addition to that, there were successful runs of `project init` yesterday on Windows:

For instance:
https://dev.azure.com/neuromation/platform-client-python/_build/results?buildId=1711&view=logs&j=e28cd8f8-d7e3-5aff-d80c-3da2a1487608&t=9efd1b7e-57a6-5945-b49c-d40b7e15d911

And:
https://dev.azure.com/neuromation/platform-client-python/_build/results?buildId=1711&view=logs&j=d9e7689b-8c30-5683-b74c-3e8cb162cd9e&t=1eb63231-203d-526e-25da-41042709fdcb

**Comment by anayden** [comment]
Fixed by https://github.com/neuromation/platform-client-python/pull/1260
