### ISSUE TITLE
Support job labels

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1273]
I need to use job description to mark jobs with different labels: 
`{project-id} {experiment-id}`
So I need to be able to filter jobs by these two labels. I also want to be able to retrieve all jobs belonging to the project `{project-id}`.

Currently `neuro ps --description` accepts the full match, which is not flexible, let's support wildcard syntax:
`neuro ps --descrpition "{project-id} *"`

**Comment by dalazx** [comment]
we could implement labels and preserve backward compatibility by converting `description` into a label on the backend side.

**Comment by ayushkovskiy** [comment]
@dalazx what do you mean by "converting description into a label on the backend side"?

From my point of view, labels indeed would make sense, but only as a separate field of `Job`, independent from job description.

**Comment by dalazx** [comment]
I mean we could have labels and deprecate the description field. the existing description values would be converted to the corresponding label.

**Comment by ayushkovskiy** [comment]
currently, we have no limitations on descrpition field, so conversion description to labels sounds not stable. Are we going to split non-empty descriptions by non-alphanumeric symbols?

**Comment by asvetlov** [comment]
tags are implemented
