### ISSUE TITLE
E2E test user names are too long

### ISSUE THREAD

**Issue by serhiy-storchaka** [neuromation/platform-client-python#1278]
User names in E2E tests like `shell-e2e-test-user-kz2lda8vctlstzarhrc9` are longer then the limit. This causes failures like:

> Failed to resolve job-name not-a-job-id resolved as name=not-a-job-id, owner=shell-e2e-test-user-kz2lda8vctlstzarhrc9 to a job-ID: String is longer than 21 characters

https://dev.azure.com/neuromation/platform-client-python/_build/results?buildId=1843&view=logs&j=e7b3dc7a-ee4c-5376-13ef-6197b8c25284&t=0fb12b3b-6b58-50b5-0e6d-6c671e87df3c&l=419

**Comment by asvetlov** [comment]
Fixed by @shagren
