### ISSUE TITLE
Move to a shorter user name for E2E tests

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#1282]
Currently we use 
```
shell-e2e-test-user-kz2lda8vctlstzarhrc9
shell-e2e-test-user-alt
```
user names but they no longer pass our user name length validation.

cc @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
See also ttps://github.com/neuromation/platform-api/issues/1063.

**Comment by shagren** [comment]
`shell-e2e-test-user-alt` not used more

**Comment by shagren** [comment]
new user created: `neuro-e2e`
new token configured to azure pipelines

@dalazx , i think we can close issue

**Comment by dalazx** [comment]
thanks @shagren! 
cc @serhiy-storchaka
