### ISSUE TITLE
Autocomplete does not work if neuro is not added to path (local installation)

### ISSUE THREAD

**Issue by tvoinarovskyi** [neuromation/platform-client-python#1283]
#### Description:
When applying patch using tools like virtualenv or pyenv and using deactivated shell later the script actually reacts to unaccessible neuro command and tries to complete it

#### Example:

* Activate virtualenv
* Do `neuro completion patch zsh`
* Deactivate virtualenv
* Try to type `neuro comp` and press TAB

Turns kind of ugly on output:
taras@Tarass-MacBook-Pro:~|⇒  neuro compyenv: neuro: command not found
The `neuro' command exists in these Python versions:
  3.7.4
  3.8.0
pyenv: neuro: command not found
The `neuro' command exists in these Python versions:
  3.7.4
  3.8.0

#### Expected behavior:
Either autocomplete does not work or continues to work as expected. Now it just raises errors or neuro not being available as a command.

#### Additional context:

It installs the function with the correct path, but inside uses simply by the name of the script:

```
_neuro_completion() {
    local -a completions
    local -a completions_with_descriptions
    local -a response
    response=("${(@f)$( env COMP_WORDS="${words[*]}" \
                        COMP_CWORD=$((CURRENT-1)) \
                        _NEURO_COMPLETE="complete_zsh" \
                        neuro )}")
    for key descr in ${(kv)response}; do
      if [[ "$descr" == "_" ]]; then
          completions+=("$key")
      else
          completions_with_descriptions+=("$key":"$descr")
      fi
    done
    if [ -n "$completions_with_descriptions" ]; then
        _describe -V unsorted completions_with_descriptions -U -Q
    fi
    if [ -n "$completions" ]; then
        compadd -U -V unsorted -Q -a completions
    fi
    compstate[insert]="automenu"
}
compdef _neuro_completion neuro;

```
Notice how inside it uses just `neuro`

**Comment by asvetlov** [comment]
this is the `click` limitation, sorry.
