### ISSUE TITLE
Add Google Measurement Protocol into CLI

### ISSUE THREAD

**Issue by astaff** [neuromation/platform-client-python#1286]
To improve user experience we would like to collect anonymous usage data using [Google Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1).

After each CLI run we should submit an [event into Google Analytics](https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#event) with category `CLI`, action `Run`, and label being a JSON capturing command line arguments and exit code. Tracking id: `UA-106571369-3`

Anonymous User ID that is passed with the HTTP call needs to be auto-generated and persisted locally.

Usage reporting should be turned on by default, however, users should be able to opt-out from sending usage data by running `neuro config opt-out`.

Upon first run of the CLI we should display the message saying: `In order to improve user experience, we are anonymously tracking usage data. You can opt-out by running "neuro confing opt-out"`. The message should be displayed once after first installation of `neuro`.

**Comment by xnutsive** [comment]
Re: `UserID`: Ideally, let's use some sort of user ID that'd be persistent between the web UI in the future, and the CLI. Since Neuro uses Auth0 to authenticate users, and CLI uses and stores an Auth0 token, the easiest way is to store the users auth0 guid (not the auth token though), and use it as a user ID. 

I'll check if Google Analytics requires the user ID to be numeric or not and report back.

**Comment by xnutsive** [comment]
We can use both `cid` and `uid`. However since we do always know `uid` (user identifier) — we can just use it, and not provide `cid`. `uid` field type is `text`, so as long as it's a unique user identifier guid / token — that should work fine. 

Auth0 [seems to have a default behavior for this](https://auth0.com/docs/users/normalized/auth0/normalized-user-profile-schema), particularly a `user_id` field.

So basically, our tracking request params would look something like this: 

```
v = 1              // Version.
&tid = UA-106571369-3  // Tracking ID / Property ID.
&uid = auth0User.user_id         // Anonymous Client ID.

&t = event         // Event hit type
&ec = CLI      // Event Category. Required.
&ea = currentCommand         // Event Action. Required.
&el = currentCommandParams     // Event label.
```

As for `ev` (event value), it's usually intended to track money, so we kind of can use it, but Google Analytics dashboard will go crazy if we do, it'll try to use these values for conversion dashboards.

**Comment by asvetlov** [comment]
1. Sending data after *every* CLI run simply means that every CLI command will be executed significantly slower.
2. Sending `user_id` violates *"we are anonymously tracking usage data"* statement. Also, I suspect that we should filter command line parameters like URIs, paths and image names to provide a satisfactory security level.

**Comment by asvetlov** [comment]
What parameters from the [list](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters) should be used? Could you provide an example of desired JSON payload?

**Comment by astaff** [comment]
@asvetlov,

Here's an example: https://ga-dev-tools.appspot.com/hit-builder/?v=1&t=event&tid=UA-106571369-3&cid=555&ec=CLI&ea=run&el=%7B%22s%22%3A%20%22gpu-small%22%2C%20%22http%22%3A%208888%7D

1. Sending the above request from the browser takes about 25ms, I view it as acceptable.
2. Agreed on both points. Let's start with anonymous ID as the first step.

**Comment by xnutsive** [comment]
@asvetlov, agreed on both points. 

I'm not sure how to address execution speed, but know for sure several other OSS CLI tools who run telemetry like that. I can ask around, specifically, iterative/dvc.

As for user privacy, Google (and most other analytics systems) require that we get a user explicit consent on tracking their product usage to 1) glue their sessions together in any analytics systems, 2) store their usage data on our or 3rd party (GA) systems. Hence, we'll need to ask for such consent at the very least on the website on their first visit. 

If someone pip installs neuro without signing up first, we'll have to ask for consent before logging them in. 

You're also right that we're violating user anonymity in a way. Just storing Auto0 User IDs in Google Analytics doesn't give Google any personally identifiable information about our users (in fact, that's a requirement of Google, we can't use user emails in GA, it's forbidden), but I can see how it doesn't read that way. 

@astaff, agreed, I think just having anonymous ids will be enough to study _just the CLI_ usage, and improve it's UX. Should we want to _glue_ web and CLI sessions together in the future — we'll have to go for user ids, and we'll probably want an opt-in mechanism for that, not opt-out.

**Comment by astaff** [comment]
We are observing CLI events in real-time view in google analytics, but were unable to see these events stored and available in Behavior section of google analytics. For troubleshooting I ran `neuro --trace ls` posted the payload into (changing `neuro ls` to `neuro test` to distinguish) and re-created the request in Hit Builder, recommended in the documentation: v=1&t=event&tid=UA-106571369-3&cid=d15d8a6a-3401-49d5-961c-7bf7794ea9d9&ds=cli&ec=CLI&ea=neuro%20test-analytics&el=%5B%7B%22trace%22%3A%20%22True%22%7D%2C%20%7B%7D%5D&an=neuro&av=20.01.22&aid=https%3A%2F%2Fstaging.neu.ro%2Fapi%2Fv1

After running the request, I confirmed that it became available in Behavior within 5 minutes.

The request below, when executed from shell, will also result in event eventually appearing in Behavior:

```
curl 'https://www.google-analytics.com/collect' -H 'authority: www.google-analytics.com' -H 'accept: */*' -H 'sec-fetch-dest: empty' -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Mobile Safari/537.36' -H 'dnt: 1' -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' -H 'origin: https://ga-dev-tools.appspot.com' -H 'sec-fetch-site: cross-site' -H 'sec-fetch-mode: cors' -H 'referer: https://ga-dev-tools.appspot.com/hit-builder/' -H 'accept-language: en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7' --data 'v=1&t=event&tid=UA-106571369-3&cid=d15d8a6a-3401-49d5-961c-7bf7794ea9d9&ds=cli&ec=CLI&ea=neuro%20curl&el=%5B%7B%22trace%22%3A%20%22True%22%7D%2C%20%7B%7D%5D&an=neuro&av=20.01.22&aid=https%3A%2F%2Fstaging.neu.ro%2Fapi%2Fv1' --compressed
```

Please make sure the request formed by python code looks like the subset of this one. I believe CLI is calling `/batch` endpoint, whereas the Hit Builder is using `/collect`

**Comment by astaff** [comment]
Upon further analysis, it stops working when `User-Agent` us removed.

The one below has a short custon `User-Agent` and doesn't have `authority`, `origin` and `referrer` and works fine. I believe we can just make the request look the same as below: 

```
curl 'https://www.google-analytics.com/collect' -H 'accept: */*' -H 'sec-fetch-dest: empty' -H 'user-agent: NeuroCLI/1.0 (Linux)' -H 'dnt: 1' -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' -H 'sec-fetch-site: cross-site' -H 'sec-fetch-mode: cors' -H 'accept-language: en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7' --data 'v=1&t=event&tid=UA-106571369-3&cid=d15d8a6a-3401-49d5-961c-7bf7794ea9d9&ds=cli&ec=CLI&ea=neuro%20 custom-agent-no-ref-orig-auth&el=%5B%7B%22trace%22%3A%20%22True%22%7D%2C%20%7B%7D%5D&an=neuro&av=20.01.22&aid=https%3A%2F%2Fstaging.neu.ro%2Fapi%2Fv1' --compressed

```
