### ISSUE TITLE
Always use UTF-8 encoding for text files

### ISSUE THREAD

**Issue by serhiy-storchaka** [neuromation/platform-client-python#1297]
Currently text files (configuration, etc) are opened with the default encoding. On Windows it is the ANSI encoding, which depends on the localization of Windows (cp1252 in many Wester countries, cp1251 in Ukraine and Russia), on Linux it is the locale encoding, which usually is UTF-8, but can be different for different users.

This makes configuration files containing non-ASCII text non-portable between different platforms and even between different users on the same computer.

It would be better to use a single portable encoding across platforms, for example UTF-8. Supporting UTF-8 with a BOM (the "utf-8-sig" encoding in Python) if it is appropriate could be even better.

**Comment by asvetlov** [comment]
FYI: the main config is converted into sqlite: #1298

**Comment by asvetlov** [comment]
I think just UTF-8 without BOM is enough.

**Comment by asvetlov** [comment]
User provided files a TOML formatted, the TOML is also UTF-8 by the standard.
