### ISSUE TITLE
Minor: `neuro submit` does not have default value for `--http`

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1315]
`neuro run`:
https://github.com/neuromation/platform-client-python/blob/78688422e6f3abe6f0287376a59e8ca3b6e346a8/neuromation/cli/job.py#L664-L671

`neuro subit`:
https://github.com/neuromation/platform-client-python/blob/78688422e6f3abe6f0287376a59e8ca3b6e346a8/neuromation/cli/job.py#L173-L175

Due to that,  `neuro run` works:
```
neuro run --no-http-auth neuromation/base jupyter notebook
```
works, but `neuro submit` does not work:
```
neuro submit --no-http-auth neuromation/base jupyter notebook
Usage: neuro submit [OPTIONS] IMAGE [CMD]...

Error: --no-http-auth requires --http
```

Also, we might want to drop `neuro submit` completely instead.

**Comment by asvetlov** [comment]
This is intentional, changing the default breaks backward compatibility.
