### ISSUE TITLE
Non cross-platform functionality: default value for job's env var

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1316]
https://github.com/neuromation/platform-client-python/blob/78688422e6f3abe6f0287376a59e8ca3b6e346a8/neuromation/cli/job.py#L101

I propose deprecation of the functionality that takes the env var value from the local machine (if there's no `=`).

**Comment by ayushkovskiy** [comment]
I found this problem on Windows: even when passing ` --env PYTHONPATH=/name-of-the-project`, somehow the job had: `PYTHONPATH=C:/Users/User/Anaconda3/Library/name-of-the-project`

**Comment by ayushkovskiy** [comment]
Reproduced only via Makefile

**Comment by asvetlov** [comment]
Please explore the problem and propose a fix

**Comment by ayushkovskiy** [comment]
I found that it's click's problem, but its root is still obscure. The problem exists only when the job (1) runs from Makefile and (2) has description:
```
.PHONY: foo
foo:
    neuro --verbose run -s cpu-small -n test --description "keks" --no-wait-start -e PPP=/path neuromation/base true
```
This target creates the following job:
```
Job: job-3777becb-988b-4a5b-aab3-66b9e3319cfa
...
Environment:
PPP=C:/Users/User/Anaconda3/Library/path
```
Note, that function `run_job()` already receives this incorrectly expanded value of `env`, so this is presumable made by `click`.

If the same command is run either from bare command line interface (Anaconda Prompt) or without `--description`, the problem disappears :confused: :
```
Job: job-50630f84-498f-4ef6-945a-a1669ec0b4d1
...
Environment:
PPP=/path
```

Also, I have found that the value `-e PPP=//path` is not getting expanded, so I think we will just patch Template instead of looking trying to fix it on click-side.

**Comment by asvetlov** [comment]
I doubt if it is a `click`: the library doesn't manipulate `PYTHONPATH` env-var at all.
Could you point on exact problematic line in source code?

**Comment by ayushkovskiy** [comment]
I don't think the problem is in `neuro` code: its CLI methods already receive the wrong value.
However, I found that the problem remains in other options as well, for example in COMMAND:
```
.PHONY: foo
foo:
        # will give wrong answer: "C:/Users/User/Anaconda3/Library/proj"
        neuro run -s cpu-small --description "foo" ubuntu echo /proj
        # will give correct "/proj"
        neuro run -s cpu-small ubuntu echo /proj
        # will give correct "/proj"
        neuro run -s cpu-small --description "foo" ubuntu echo //proj
        # will give correct "//proj"
        neuro run -s cpu-small ubuntu echo //proj
```
On localhost, `echo /proj` prints correct value.

**Comment by serhiy-storchaka** [comment]
What if use the short form `-d`?

**Comment by serhiy-storchaka** [comment]
What if use other paths, for example `/zip`?

`/` starts an option on Windows, and there is an option `-p` (`--preemptible`).
