### ISSUE TITLE
Ctrl-C does not always work on Windows

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1318]
Use-case: on Windows, run a job and attach logs to it. Ctrl-C won't work even if pressed multiple times.

Quick workaround suggested by @tvoinarovskyi : on Windows, run a background infinite loop task to make Python process syscalls with delay at most 1 sec:
```
async def infinite():
    try:
        while True:
            await asyncio.sleep(1)
    except asyncio.CancelledError:
        return
```

**Comment by asvetlov** [comment]
Fixed by Python 3.8

**Comment by ayushkovskiy** [comment]
What about other versions? Do we require our users to use only Python 3.8? If not, I think we need to consider the fix.

**Comment by asvetlov** [comment]
Feel free to provide a pull request.
Your help is very appreciated.
