### ISSUE TITLE
Reusing resource options for 'neuro model'

### ISSUE THREAD

**Issue by shagren** [neuromation/platform-client-python#135]
#### Is your feature request related to a problem? Please describe.
When you create many experiments with code and data  you use same hardware requirements (gpu, cpu, memory, shm option) often. You need to pass same options each time for _neuro model train_.
You can simplify workflow by using some wrapper/start script.

#### Describe the solution you'd like
We can support _presets_ which user can configure and use, i.e.:
```
  neuro preset add Small -g 0 -c 0.1 -m 512
  neuro model train --preset Small ...
  ...
  neuro model update default -c 2
  neuro model train ...
```

#### Describe alternatives you've considered
We can store and reuse latest options globally or per dir(project).

**Comment by asvetlov** [comment]
The command is gone
