### ISSUE TITLE
`neuro ps -a` takes hours for admin user on dev env

### ISSUE THREAD

**Issue by asvetlov** [neuromation/platform-client-python#1374]
Because there are too many finished jobs available for this user.
We need to invent some logic for shrinking the list size.

I see possible options like adding filters for job start and job finish time etc, pagination, finished jobs cleanup, etc.

We need to discuss the strategy before starting the implementation.

/cc @dalazx

**Comment by serhiy-storchaka** [comment]
We could output by default only jobs created a week ago (as for completion) if `-a` is used.
