### ISSUE TITLE
Partially non-working resource URIs with cluster-name

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1404]
Environment: `staging`.

### Non-working scenario:
User `test1` shares a resource with user `test2`:
```
test1> neuro share storage:abc test2 manage
```
User `test2` sees the resource permissions:
```
test2> neuro acl list | grep abc
storage://test1/abc manage
```
But the resource URL should be `storage://neuro-ai-public/test1/abc`.

Neither with nor without cluster-name in URI works:
```
test2> neuro ls storage://test1/abc
ERROR: cannot access storage://test1/abc: 404: Not Found
test2> neuro ls storage://neuro-ai-public/test1/abc
ERROR: cannot access storage://neuro-ai-public/test1/abc: 404: Not Found
```

### Working scenario:
User `test1` shares a resource with user `test2` via full link:
```
test1> share storage://neuro-ai-public/test1/def test2 manage
```
User `test2` sees the resource permissions:
```
test2> neuro acl list | grep def
storage://neuro-ai-public/test1/def manage
```
User  `test2` CAN NOT access the resource via full URI:
```
test2> neuro ls storage://neuro-ai-public/test1/def
ERROR: cannot access storage://neuro-ai-public/test1/def: 404: Not Found
```
Although `test2` CAN access the resource via shortened URI (wihtout cluster-name):
```
test2> neuro ls storage://test1/def
```
### Small note:
when sharing a job, `neuro share job:job-id test2 read` works. 

We need to re-view all URIs used by the client and verify that we resolve all shortened URIs correctly:
- `storage:path` -> `storage://cluster-name/user-name/path`, 
- `job:job-id` -> `job://cluster-name/user-name/job-id`, 
- `image:ubuntu` -> `image://cluster-name/user-name/ubuntu`.

**Comment by serhiy-storchaka** [comment]
Yes, it is a known issue. And it will be solved by #1342.

The workaround is to share resources in two forms: `storage://user-name/path` and `storage://cluster-name/user-name/path`. We expect that not much resources are shared and for all shared resources the other form may be shared manually either by the original owner or by admin.
