### ISSUE TITLE
Implement more standard filter patterns

### ISSUE THREAD

**Issue by serhiy-storchaka** [neuromation/platform-client-python#1444]
There are several issues with filters:

* `?` matches `/`. So `a?c` matches `abc` as well as `a/c`.
* `*` matches sequences containing `/`. So `a*z` matches `abz`, `a/z`, `ab/yz`, `ab/c/yz` etc.
* To match files in subdirectories you have to prepend `*/`: `--exclude '*.tmp' --exclude '*/*.tmp'`.

We have to implements semantic used in `.gitignore`.

* Make `?` and `*` not matching `/`.
* Add support of `**` for recursive matching.
* Make patterns not containing slashes except the trailing slashes recursive (virtually prepend implicit `**/` to them).

**Comment by yartem** [comment]
How about to be able to specify files with `.gitignore`-like syntax? When I was implementing `--exclude` in Template, I felt real need to ignore everythin from `.gitignore` except some files.

So for example:
```
neuro cp -r --exclude-from=".gitignore" --include="*.log" ...
```

We could re-use existing gitignore parsers, for example https://github.com/mherrmann/gitignore_parser

**Comment by serhiy-storchaka** [comment]
This is a next stage.
