### ISSUE TITLE
Add support of .neuroignore

### ISSUE THREAD

**Issue by serhiy-storchaka** [neuromation/platform-client-python#1446]
Currently we can specify filters for file transferring operations either via CLI options (`--exclude` and `--include`) or via the neuro configuration file (see `neuro help user-config`). It may be convenient to specify filters for particular projects, using well known format. There was proposed an idea about using `.gitignore` for this purpose, but it was rejected, because filters for `git` and `neuro` may be different. There was proposed other idea about using `.neuroignore` files with the same format and and semantic as `.gitignore` (see #1182). They will not conflict with `.gitignore`.

**Comment by yartem** [comment]
I still think that it's very convenient to re-use `.gitignore` itself (and further `.git/info/exclude`), at least with a separate flag: `--include-gitignore` (by default, not uploading anything git-ignored). This feature can live along with `.neuroignore`.

**Comment by yartem** [comment]
+ not forget to ignore `.git` directory itself.

**Comment by yartem** [comment]
Let's allow inclusion of `.gitignore`, `.dockerignore` and potentially other files.

Usage: Don't have any additional options (like `--include-gitignore`). Instead, explicitly list files to process in `.neuro.toml`:
```
[storage]
cp-exclude = ["file1.txt"]
cp-ignore = [".gitignore", ".dockerignore", "data/.gitignore"]
```

Problem: what to do in case of conflicts? For example, `.gitignore` has entry `!/data/data.txt`, whereas `data/.gitignore` has entry `data/data.txt`.

Possible solutions:
1. When processing ignore-files, use the **first** rule and print warning that the later rule will be ignored
2. When processing ignore-files, use the **later** rule and print warning that the first rule was overwritten
3. Use interactive prompt, which can be defaulted to either `1.` or `2.` in `.neuro.toml`

I think, we could stick to a non-interactive solution, which implements both `1.` and `2.` options:
```
[storage]
cp-ignore = [".gitignore", ".dockerignore", "data/.gitignore"]
cp-resolve-conflicts = "use-first"  # or "use-last"
```
