### ISSUE TITLE
Relative URI: no way to access ohter user's resources

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1452]
Before, `storage:foo` meant `storage://user/foo`, but now, after we introduced cluster name in URIs, it means `storage://cluster/user/foo`. So now, there's no way to address other user's resources without defining cluster name: `storage://cluster/another-user/foo`. 

Let's reserve one slash for that:
`storage:/another-user/foo` will mean `storage://cluster/another-user/foo`

cc @asvetlov

**Comment by serhiy-storchaka** [comment]
Implemented in #1425.
