### ISSUE TITLE
Add the --restart option to neuro run/submit and API

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#1459]
See https://github.com/neuromation/platform-api/pull/1180

We'd like to have another option to specify the restart policy for the job similarly to what docker provides: 
https://docs.docker.com/engine/reference/run/#restart-policies---restart
the values, though, are slightly different: `always`, `on-failure` and `never`. `never` is the default one.
we could also support `no` and translate it to `never`.

we should also output this field in `neuro status`.

**Comment by serhiy-storchaka** [comment]
Closed by #1484.
