### ISSUE TITLE
For On-Prem cluster GPU models can be specified arbitrary

### ISSUE THREAD

**Issue by tvoinarovskyi** [neuromation/platform-client-python#1474]
#### Description:
Currently explicit job run configuration for `--gpu` option is limited to a set of predefined GPU models:
https://github.com/neuromation/platform-client-python/blob/master/neuromation/cli/defaults.py#L8
This will not work for custom On-Prem clusters, as GPU models can be quite arbitrary. We should remove the constraint and validate the list against Cluster configuration instead.

#### Example:
neuro submit --gpu-model custom-nvidia-xxx ...

#### Expected behavior:
GPU model should be validated against the models of the cluster you launch it on.

**Comment by asvetlov** [comment]
We are getting rid of `neuro submit` command entirely, won't fix
