### ISSUE TITLE
Feature: disable scheduling timeout with CLI

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1499]
Pass API parameter
https://github.com/neuromation/platform-client-python/blob/1057b68e6c4c9588a1ea4d72450315b0ce9d18d0/neuromation/api/jobs.py#L156
to CLI:
https://github.com/neuromation/platform-client-python/blob/1057b68e6c4c9588a1ea4d72450315b0ce9d18d0/neuromation/cli/job.py#L1142

**Comment by serhiy-storchaka** [comment]
What exactly feature do you need?
```
--schedule-timeout TIMEDELTA
```
or
```
--no-schedule-timeout
```
which sets `schedule_timeout` to minimum (1 sec) or maximum (some large number)?

It is not clear to me what is needed.

**Comment by serhiy-storchaka** [comment]
#1623 adds the `--schedule-timeout` option, but I am not sure that it is what you want.
