### ISSUE TITLE
Neuro-cp of a large archive automatically restarts before being finished

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1521]
Bug from @atselousov.

Run`neuro cp -r storage://.../directory ./` without restarts, with time the archive that waw already downloaded 43% automatically became 0.6%. Command was not interrupted.

See for example the first archive `zip4.zip`: 

![Screenshot from 2020-06-02 13-02-26](https://user-images.githubusercontent.com/7501517/83509540-440dd280-a4d4-11ea-8dd5-894173c09a94.png)

![Screenshot from 2020-06-02 13-11-37](https://user-images.githubusercontent.com/7501517/83509536-42dca580-a4d4-11ea-9aa7-42baa74c8931.png)

I have no information whether the downloaded binary data was actually dropped or the problem is only with percentage reporting.

**Comment by atselousov** [comment]
It looks like `neuro cp` command gives up on downloading a file at some point and starts downloading it again. But on the other side, the size of the processing file on the disk increases on the amount which `neuro cp` shows after the restart. 

There is an example (look at zip.zip file):
* output of `ls -lh` just after a restart:
![Screenshot from 2020-06-02 16-31-33](https://user-images.githubusercontent.com/22117239/83526213-c2776e00-a4ee-11ea-8a09-a5a4e45567ba.png)

* output of `ls -lh` just in some time and `neuro cp` output:
![Screenshot from 2020-06-02 16-21-41](https://user-images.githubusercontent.com/22117239/83526227-c7d4b880-a4ee-11ea-9764-21ca3a619b91.png)
![Screenshot from 2020-06-02 16-21-53](https://user-images.githubusercontent.com/22117239/83526235-cacfa900-a4ee-11ea-80a5-9292e7704001.png)

**Comment by atselousov** [comment]
In some time the size of a file after a restart on the local machine becomes even more than the size of the original file on the storage. So, it's not just an error of percentage reporting.

There is an example (look at zip2.zip):
* The size on the local machine
![Screenshot from 2020-06-02 17-31-43](https://user-images.githubusercontent.com/22117239/83532646-374ea600-a4f7-11ea-8ee0-7b2c7a913299.png)
![Screenshot from 2020-06-02 17-31-55](https://user-images.githubusercontent.com/22117239/83532657-3a499680-a4f7-11ea-8890-87d0c73de953.png)

* The size on the storage:

![Screenshot from 2020-06-02 17-32-53](https://user-images.githubusercontent.com/22117239/83532672-3ddd1d80-a4f7-11ea-9e2f-60bc050568d9.png)

And downloading is still going on.
