### ISSUE TITLE
Broken dependency with cookiecutter and airflow

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1529]
Problem:
```
$ pip install -U apache-airflow neuro-airflow-plugin
...
$ airflow
Traceback (most recent call last):
  File "/home/ay/.pyenv/versions/3.7.6/bin/airflow", line 25, in <module>
    from airflow.configuration import conf
  File "/home/ay/.pyenv/versions/3.7.6/lib/python3.7/site-packages/airflow/__init__.py", line 97, in <module>
    operators._integrate_plugins()
  File "/home/ay/.pyenv/versions/3.7.6/lib/python3.7/site-packages/airflow/operators/__init__.py", line 104, in _integrate_plugins
    from airflow.plugins_manager import operators_modules, register_inbuilt_operator_links
  File "/home/ay/.pyenv/versions/3.7.6/lib/python3.7/site-packages/airflow/plugins_manager.py", line 194, in <module>
    plugins
  File "/home/ay/.pyenv/versions/3.7.6/lib/python3.7/site-packages/airflow/plugins_manager.py", line 104, in load_entrypoint_plugins
    plugin_obj = entry_point.load()
  File "/home/ay/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2461, in load
    self.require(*args, **kwargs)
  File "/home/ay/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2484, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/ay/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (text-unidecode 1.2 (/home/ay/.pyenv/versions/3.7.6/lib/python3.7/site-packages), Requirement.parse('text-unidecode>=1.3'), {'python-slugify'})
$ pip --version
pip 20.1.1 from /home/ay/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pip (python 3.7)
```
Broken dependencies:
(`->` means `requires`)
`neuro-airflow-plugin==0.0.1` -> [`neuromation>=20.4.6`](https://github.com/neuromation/platform-airflow/blob/308e3a41e1567c52161b802343add1c42fc2846a/setup.py#L6) -> [`cookiecutter==1.7.2`](https://github.com/neuromation/platform-client-python/blob/dfe74a9614732a02ffdd1a8652db37dedc23e94a/setup.py#L44) -> [`python-slugify>=4.0.0`](https://github.com/cookiecutter/cookiecutter/blob/591779157a62bafbb0655b32d8e86e6b3a32e869/setup.py#L16) (this dependency appeared in version [1.7.2](https://github.com/cookiecutter/cookiecutter/commit/71b91263d5656c71c9dff8a964806968c37e66cf) -> [`text-unidecode>=1.3`](https://github.com/un33k/python-slugify/blob/d1599a799d551d6bf57b1a727af10c125fc6a257/setup.py#L17). 
In turn, `apache-airflow` requires [`text-unidecode==1.2`](https://github.com/apache/airflow/blob/1c9374d2573483dd66f5c35032e24140864e72c0/setup.py#L721).

I think, `neuro` doesn't need to have strict dependency `cookiecutter==1.7.2`, we can go with lower versions. I think we should go with `cookiecutter>=0.9.0,<=1.7.1`.

I tested `cookiecutter==0.9.0`:
```
$ python -c 'from cookiecutter.main import cookiecutter; cookiecutter("gh:neuromation/cookiecutter-neuro-project", checkout="release", extra_context={}, no_input=True)'
```

**Comment by yartem** [comment]
working combination: `neuro-airflow-plugin==0.0.1`, `neuromation>=20.4.6`, `apache-airflow==1.10.10`

**Comment by asvetlov** [comment]
Is the problem solved?

**Comment by yartem** [comment]
it will be solved when we release `neuro` and then release the new `neuro-airflow-plugin` with requirement `neuromation>20.6.2`

**Comment by yartem** [comment]
JFYI: added issue for cookiecutter's repo: https://github.com/cookiecutter/cookiecutter/issues/1426
