### ISSUE TITLE
Implement secret management commands 

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#1545]
**neuro secrets** shows the list of the user's secrets.
```
GET https://dev.neu.ro/api/v1/secrets
```

**neuro secrets add <KEY> <VALUE>** adds a new secrets or replaces an existing one given its key.
```
POST https://dev.neu.ro/api/v1/secrets
{
    "key": "<KEY>",
    "value": "BASE64ENCODED(<VALUE>)"
}
```

**neuro secrets remove <KEY>** removes the secret by its key.
```
DELETE https://dev.neu.ro/api/v1/secrets/<KEY>
```

The backend codebase: https://github.com/neuromation/platform-secrets/blob/ca8e3c3eb9ce8168e09c7ec335b613e64e58e83f/platform_secrets/api.py#L92-L122

**Comment by dalazx** [comment]
@asvetlov @shagren 
Any ideas on how to pass binary values via CLI?

**Comment by shagren** [comment]
You mean next?
```
curl  https://example.com -X POST --data "{\"key\": \"test\", \"value\": \"$(cat ~/.profile | base64)'\"}"
```

**Comment by dalazx** [comment]
yep, but using CLI. I remember you suggested using @filename.ext similarly to curl.
@asvetlov what do you think?

**Comment by shagren** [comment]
You mean `neuro cli`. 
I see two options:
```
neuro secrets update secret-name text-value
neuro secrets update secret-name @file.ext
vs
neuro secrets update secret-name text-value
neuro secrets update secret-name --file=file.ext 
```

**Comment by dalazx** [comment]
thanks @shagren 
I like the second variant more. up to @asvetlov to decide.
