### ISSUE TITLE
Patch `neuro run` to allow specifying secrets

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#1558]
```shell
neuro run --secret-volume <KEY>:/mount/path --secret-env <NAME>=<KEY>
```

alternatively, but somewhat more complex
```shell
neuro run -v secret:<KEY>:/mount/path -e <NAME>=secret:<KEY>
```

The backend implementation can be found here: https://github.com/neuromation/platform-api/pull/1235

**Comment by asvetlov** [comment]
I like the second alternative.

**Comment by serhiy-storchaka** [comment]
`-e <NAME>=secret:<KEY>` conflicts with `-e <NAME>=<VALUE>`.

**Comment by yartem** [comment]
Considerations (would work with either format of two listed above):

1. I think it's better UX if the secret key is not deduced from the filename but explicitly passed as the secret name:
```
$ neuro secrets add secret1 --from-file /path/to/file.txt
sends {"key": secret1, "value": base64(filecontent)}
$ neuro secrets add secret2 --from-literal foo
sends {"key": secret2, "value": base64(foo)}
$ neuro run ... --secret-file secret2=/var/sec/file.txt --secret-env secret1=SECRET_ENV
```
Note: in this case, `--from-literal` will different from k8s' similar command.

2. each secret, that is to be mounted to the job, can be mounted to different mountpoints:
```
neuro run --secret-file=secret1:/var/sec1/file1.txt --secret-file=secret2:/var/sec2/file2.txt
```

3. secret name should not have `/` characters so that:
```
assert PurePath(URL(secret_name).path).parts[0] == secret_name
```


4. API format for secret-volume:
```
$ neuro run ... --secret-file secretname=/var/sec/file.txt 
```
```
{
  "secret_volumes": [
    {
      "src_secret_uri": "secret://CLUSTER/USER/secretname",
      "dst_path": "/var/sec/file.txt"
    }
  ]
}
```
4. API format for secret-env:
```
$ neuro run ... --secret-env secretname=ENV_NAME 
```
```
{
  "secret_env": {
    "ENV_NAME": "secret://CLUSTER/USER/secretname"
  }
}
```

**Comment by asvetlov** [comment]
> `-e <NAME>=secret:<KEY>` conflicts with `-e <NAME>=<VALUE>`.

I think this is an acceptable tradeoff.
I very doubt if people use "secret:something" as an environment value right now. On the other hand, non-existing key in "NAME=secret:key" can be quickly and explicitly reported by server.

**Comment by dalazx** [comment]
another interesting point related to the alternative variant is that it will allow us to implement sharing secrets within a cluster if needed.

**Comment by yartem** [comment]
why wouldn't the second option allow us sharing secrets in the future? In the form `-d KEY=secret:VAL`, `secret:VAL` is a URI, so to use other user's secret one could `-d KEY=secret:/username/VAL`
