### ISSUE TITLE
Impossible to create a disk

### ISSUE THREAD

**Issue by daria-moskovskykh** [neuromation/platform-client-python#1730]
Impossible to create a disk:

```
neuro disk create 500Mi
ERROR: Unable parse value: 500Mi
neuro disk create 500Mb
ERROR: Unable parse value: 500Mb
neuro disk create 500M
ERROR: Illegal argument(s) (could not convert string to float: '524288k')
```

Also, there is an error Examples, Gi/Mi isn’t supported, should be M / Mb (M = 1024 * 1024, MB = 1000 * 1000)

```
Usage: neuro disk create [OPTIONS] STORAGE

  Create disk with storage amount STORAGE.

Examples:
  neuro disk create 10Gi
  neuro disk create 500Mi
```

MacOS Catalina 10.15.6

**Comment by romasku** [comment]
```
neuro disk create 500M
ERROR: Illegal argument(s) (could not convert string to float: '524288k')
```
This was problem on server (it was unable to parse response from k8s), should be fixed by this commit https://github.com/neuromation/platform-disk-api/commit/ed3c55218071f2c5602342330f6a9916b73af77d.

Also created PR that properly documents STORAGE argument format.

**Comment by serhiy-storchaka** [comment]
The Kubernetes [code](https://github.com/kubernetes/kubernetes/blob/6b963ed9c841619d511d2830719b6100d6ab1431/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L30) contradicts its [documentation](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/resources.md):

> To make life easier for people, quantities can be represented externally as unadorned integers, or as fixed-point integers with one of these SI suffices (E, P, T, G, M, K, m) or their power-of-two equivalents (Ei, Pi, Ti, Gi, Mi, Ki).

> Case is significant: "m" and "M" are not the same, so "k" is not a valid SI suffix.
