### ISSUE TITLE
Output after removing a disk

### ISSUE THREAD

**Issue by daria-moskovskykh** [neuromation/platform-client-python#1735]
There is no output after removing a disk.
See the screenshot https://monosnap.com/file/ggphK5dEMs41dypqDMXbSkLqZCdk8I

**Comment by asvetlov** [comment]
@romasku please apply this tiny change

**Comment by romasku** [comment]
I also checked how we handle other `rm` commands:
- `neuro secrets rm` has no output
- `neuro storage rm` only prints deleted files if `-v` (verbosity flag) is set
- And after https://github.com/neuromation/platform-client-python/pull/1738 `neuro disk rm` will always print "disk was removed".

Probably we should unify these behaviors. @asvetlov what do you think?

**Comment by asvetlov** [comment]
I like printing when `-v` is set only everywhere.
Or, at least, we should skip printing if `-q` is passed.
