### ISSUE TITLE
Implement confirmation for neuro job kill

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#196]
This is mainly to not accidentally delete jobs after wildcard filtration.
Also add an ability to force deletion.

**Comment by asvetlov** [comment]
@dalazx do you still think that the feature is important for us and should be implemented soon?

**Comment by yartem** [comment]
AFAIK we didn't implement wildcards in `neuro ps --description`, so I think we don't need confirmation.

**Comment by asvetlov** [comment]
Sorry, I've missed "wildcard" word on the first reading
