### ISSUE TITLE
Bug during heavy drive usage

### ISSUE THREAD

**Issue by adavydow** [neuromation/platform-client-python#263]
I ran a job while copying a large folder from nfs mounted in the container.
```
< neuro job status job-92279bec-6fe2-48cb-a47c-8d59e7107ac0  # check job status
> ERROR: Illegal argument(s) (Service Unavailable)
```
It was for our legacy nfs. Do not know if it is reproducible for gfs.

**Comment by asvetlov** [comment]
I think we can close it
