### ISSUE TITLE
Make error messages more informative

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#271]
Discussion: https://github.com/neuromation/platform-api-clients/pull/265#discussion_r238247066
Instead of printing "Invalid image name format: job-id..." the client should print what is exactly the problem it faces. 

Note: This work should start with server who should send informative errors, which exactly file was not found, etc. etc.
Note 2: When implementing this on the server, beware not to reveal internal information that might be somehow sensitive (absolute paths on the server, etc. etc.)

**Comment by asvetlov** [comment]
Fixed. If you see something missed -- please file a new issue with the specific error report
