### ISSUE TITLE
-f option for neuro job monitor (future neuro log)

### ISSUE THREAD

**Issue by adavydow** [neuromation/platform-client-python#432]
#### Is your feature request related to a problem? Please describe.
Sometimes we do not want to stream log, just read what is already here.
#### Describe the solution you'd like
Non-streaming behaviour can be default one, and `-f` can activate streaming (like `tail -f` or `kubectl log -f`).
#### Describe alternatives you've considered
Currently streaming behaviour is default (and only)  and we can keep it this way, deactivating it with a key, but I think it's better to mimic existing tools.

**Comment by asvetlov** [comment]
Closing. If somebody will ask for explicit non-streaming mode -- we can consider it.
