### ISSUE TITLE
Wrong exception: IllegalArgumentError

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#512]
Here:
https://github.com/neuromation/platform-api-clients/blob/master/python/neuromation/cli/main.py#L192-L194
we need to refactor the hierarchy of client exceptions, IllegalArgumentError is wrong for some cases, for example: `aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway'`
(here https://circleci.com/gh/neuromation/platform-api-clients/2112)

**Comment by shagren** [comment]
@ayushkovskiy I think it's already done
