### ISSUE TITLE
Add E2E tests that check GPU availability

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#554]
We need to periodically run E2E tests that check GPU availability. These tests would be disabled for PRs by default.

One suggestion would be to run 10 concurrent GPU-enabled jobs to see availability.
But we have to be sure our tests cleanup logic works well.

Potentially we could use yet another user + token and have a CI backed cleanup.

cc @alin999 @shagren

**Comment by shagren** [comment]
I think it's covered by https://github.com/neuromation/platform-metrics-tts/ and can be closed
