### ISSUE TITLE
Order of columns in `neuro ps` should be the same as in `docker ps`

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#627]
I think, we need to enclose `neuro ps` output to `docker ps` as much as possible, because most neuro-users will be also usning docker (at least for creating and debugging their images).

So, we should at least set up the same order of columns in `ps` command.

Now it's as following:
```$ neuro ps
ID  NAME  STATUS  WHEN  IMAGE  DESCRIPTION  COMMAND
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES```

**Comment by shagren** [comment]
@dalazx let's close due @ayushkovskiy inactivity :)

**Comment by ayushkovskiy** [comment]
OK Let's reconsider default columns after the https://github.com/neuromation/platform-client-python/issues/1021 is implemented (for example, I want to throw out DESCRIPTION field)

**Comment by ayushkovskiy** [comment]
... and we can customize the columns not necessarily in the order of `docker ps` but in order we find more beautiful.
