### ISSUE TITLE
Wrong job creation time on neuro ps

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#643]
Maybe because of differences in timezones, the client calculates the job creation time wrongly sometimes.

**Comment by shagren** [comment]
@ayushkovskiy can you reproduce now?

**Comment by ayushkovskiy** [comment]
Sorry I cannot reproduce either. I run a job, switch the timezone (`timedatectl set-timezone America/New_York`), look at `neuro ps` output and see `5 minutes ago`. Closing.
