### ISSUE TITLE
Review messages: technical correctness + English grammar + style

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#664]
We need to make a review (style + English) of all messages we print (in projects platform-api-clients, platform-api, maybe others) and help messages. 

see discussion https://neuromation.slack.com/archives/C9Z1UBC6A/p1553513914085500

**Comment by asvetlov** [comment]
The issue is toooo generic.
Please report about concrete problems, not about a wish to get everything perfect.
