### ISSUE TITLE
We need a simple way to upload a local/remote dataset on a platform.

### ISSUE THREAD

**Issue by adavydow** [neuromation/platform-client-python#668]
At the moment uploading dataset to a platform is not an easy task: `cp -r` is too slow and can not recover from connection error. There are several workarounds but they require lot's of interactions and monitoring. It'll be great to have a fire-and-forget command, so we can do something else while the dataset is uploading.

**Comment by asvetlov** [comment]
`neuro cp` is much-much faster now
