### ISSUE TITLE
Logout from auth0 on neuro logout

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#680]
During `neuro login`, the user clicks "Login via GitHub" in browser. If the user was not granted access to neuromation platform, they will see the following error page:
```
Failed to create a user: {"error":"user \"ajuszkowski\" already exists"}
```
So now the user realizes that they needed to login via Google account instead, so they run `neuro logout` (which cleans local auth information), and then they run again `neuro login`, but the browser already stores cookies for `staging-neuromation.auth0.com` and automatically logs the user in back to GitHub account. So the only workaround is to clean cookies and `neuro login` again.

**Comment by asvetlov** [comment]
We still need it

**Comment by asvetlov** [comment]
auth0 has an endpoint for logging out, we shall open this URL in a browser on `neuro logout`
