### ISSUE TITLE
Simplify bug reporting via the CLI tool

### ISSUE THREAD

**Issue by anayden** [neuromation/platform-client-python#725]
#### Is your feature request related to a problem? Please describe.
We would like to simplify bug reporting process for users. At the moment they're required to remember to run diagnostics such as `neuro --version` and `neuro config show` and then manually navigate to the issue creation UI.

#### Describe the solution you'd like
Having a special CLI command, e.g. `neuro bug-report` that populates all required information and guides them to the issue creation on GitHub might increase our issue quality.

**Comment by asvetlov** [comment]
Nobody had found free time for this task.
I'd like to close it for now.
We can return to the issue when will have confidence in the proposal's urgency.
