### ISSUE TITLE
Simplified/probably synchroneus API for python

### ISSUE THREAD

**Issue by adavydow** [neuromation/platform-client-python#847]
At the moment our python API is pretty hard to use, especially for a user who is not familiar wyth asyncio.
For instance @Rauf-Kurbanov had lots of problem while trying to start an rsync job from a python script.
If we want others to use our python API some reorganisation/documentation and maybe a synchroneous version is needed.

**Comment by asvetlov** [comment]
The API was significantly refactored and documented
