### ISSUE TITLE
neuro upload / faster neuro cp

### ISSUE THREAD

**Issue by Rauf-Kurbanov** [neuromation/platform-client-python#865]
#### Problem statement
At the moment, neuro platform provides no way to download large files, whether datasets or simply large repositories. It is possible of course: you can use `neuro cp` which will take forever, or use any other trick you would use with a general remote machine.
This is crucial as for new users when getting started with their own dataset as for experienced engineers, using platform as part of ci of syncing large local repos.

#### Considered alternative
As I understood from discussion with @adavydow and @asvetlov the most reliable way to do this would be to make fundamental changes to `neuro cp`, but it would be very large and time consuming task.

#### Proposed solution
What I propose is just to implement a simple script as a platform plugin using remote host with rsync. I already have a workaround using console interface: https://github.com/neuromation/environments/blob/neuro_upload/scripts/upload.mk which is good enough for ci and incremental upload but is still quite unstable, ad hoc and hard to share with other users.

I tried to reimplemented it on python https://github.com/neuromation/environments/blob/neuro_upload/scripts/neuro_upload.py but faced a lot of struggles with client's private API, asynchronous paradigm and lack of examples.
I would not expect average platform user to be more technically experienced than me and be willing to do this himself.

#### Related issues
https://github.com/neuromation/platform-api/issues/660
https://github.com/neuromation/platform-api/issues/151 (one of the oldest issues)

**Comment by asvetlov** [comment]
Outdated
