### ISSUE TITLE
Improve neuro ps to output additional columns

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#874]
if the job list consists of the jobs that:
1. belong to different owners;
2. belong to different clusters;
we want to distinguish them by rendering the corresponding column with different values.

**Comment by shagren** [comment]
not blocked now

**Comment by astaff** [comment]
Let's get it integrated. It's needed in reports

**Comment by ayushkovskiy** [comment]
Note, `owner` field was added in PR https://github.com/neuromation/platform-client-python/pull/1000

**Comment by ayushkovskiy** [comment]
I think we better not distinguish whether the jobs of the output of `neuro ps` has one or more owners/clusters, but allow users to manually chose what they want to see in the output (see https://github.com/neuromation/platform-client-python/issues/1021). So I propose to implement this feature in the same release as the feature that adds new fields to the output (such as cluster-name).

**Comment by shagren** [comment]
I think than colums autohiding will be cool feature for UX, user will see more relevant infomation on limited by width terminal. Related issue is more about parsing output by some scripts

**Comment by mariyadavydova** [comment]
For me, autohiding is very confusing feature, because two given users may have different format of output running the same command.
@shagren Can you give an example of columns autohiding in some popular CLI?

**Comment by shagren** [comment]
@mariyadavydova, I cannot provide examle :(

**Comment by mariyadavydova** [comment]
Let's omit this "columns autohiding" feature for now then. 
However, as the `neuro ps` output becomes more and more detailed, I would opt for implementing #1021 ASAP.

**Comment by shagren** [comment]
I think this issue resolved. Now `neuro ps` always display columns `owner` and `cluster`
@dalazx , let's close
