### ISSUE TITLE
neuro run/submit and neuro exec should be consistent wrt attaching to remote

### ISSUE THREAD

**Issue by anayden** [neuromation/platform-client-python#931]
`neuro run/submit` attaches to started container by default (just like `neuro logs` does), but doesn't do it when `--detach` option is supplied.
`neuro exec` does the opposite: doesn't attach by default, but attaches with `-t` is supplied.

I believe these subcommands should have consistent behavior in that regard.

**Comment by asvetlov** [comment]
Fixed by #932
