### ISSUE TITLE
`storage load`: `-r` vs `-u` 

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/platform-client-python#948]
ATM it is not possible to use `-r` and `-u` together. 
If you want to sync a directory, you use `-u`. 
For me, this looks rather unexpected. Let's reconsider the relations between these two options.
```
  -r, --recursive                 Recursive copy, off by default
  -u, --update                    Copy only when the SOURCE file is newer than
                                  the destination file or when the destination
                                  file is missing
```

**Comment by asvetlov** [comment]
The command is deprecated and scheduled for removal
