### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by arthurmccallum** [neuromation/platform-client-python#964]
#### Description:
Cannot log in to neu.ro through web or CLI. Error messages below. 

#### Example:
Using single sign on (neuromation through google) - 2x today I logged in successfully and attempted to run the fast.ai course (which is not there). I then again attempted to log in @~15:00 ET and received an error message in the web interface: “Something went wrong  Sorry, something went wrong there. Try again.” Tried multiple times. 

Attempted login through the CLI, same error. I logged out through CLI, restarted CLI terminal restarted chrome. Same error. Then restarted the computer. Same error. I then tried to login through github, and got a different error:

Last login: Mon Aug 19 14:54:04 on console
(base) ArchiMacBookPro:~ arthurleemccallum$ neuro ps
ERROR: Config file /Users/arthurleemccallum/.nmrc does not exists. Please login
(base) ArchiMacBookPro:~ arthurleemccallum$ neuro login
ERROR: Failed to create a user: {"error":"user \"arthurmccallum\" already exists"}

#### Expected behavior:
Expected to log in. 

#### Additional context:
Note that I updated neuro today as per Svetlov's instructions. I also followed CLI prompts to make Certifi update. First time did not work, second time did work.

**Comment by dalazx** [comment]
@arthurmccallum thank you for filing the issue!

what we are observing here is essentially two problems:
1. [`Auth0` rules time out](https://github.com/neuromation/platform-ingress-auth/issues/40) which is a minor issue;
2. Currently we do not automatically merge different identity provider accounts of the same user.

**Comment by arthurmccallum** [comment]
@dalazx: thank you - two for one! This morning I was able to log in from my mobile (chrome), then laptop (chrome), with no issue. Note: once logged in through chrome, when opening the CLI, neuro ps gave: ERROR: Config file /Users/arthurleemccallum/.nmrc does not exists. Please login. I logged in from the CLI and all seems fine.

**Comment by dalazx** [comment]
@arthurmccallum login in `https://neu.ro` and `neuro login` are unrelated, therefore one needs  to `neuro login` regardless of whether they were previously logged in to the web site.

**Comment by arthurmccallum** [comment]
@dalazx. thanks. Logging in to the CLI triggers browser to open a new tab with neu.ro and scroll down the page, which made me think they were linked. But I see that the CLI login does not drive a log in through neu.ro.

**Comment by dalazx** [comment]
@arthurmccallum we could potentially convert this into the following flow:
1. a user hits `neuro login` which triggers a new tab with the consent screen;
2. then the user gives their consent and signals `neuro login` to proceed;
3. `neuro login` triggers a redirect which in turn **triggers the web site login**.
thus the experience might seem more connected.

cc @astaff

**Comment by asvetlov** [comment]
outdated
