### ISSUE TITLE
Make a Cookiecutter for the Project Template

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/platform-client-python#966]
Extract a project template as a cookiecutter template from [benchmark project](https://github.com/neuromation/platform_benchmark/tree/neuro-template). 

Update the base image accordingly.

Additional information:

* [Template overview](https://github.com/neuromation/platform_benchmark/blob/neuro-template/Template.md) contains all required information as well as a list of TODOs yet to be done with this template. Please resolve TODOs before extracting the template.

* [Feature proposal](https://docs.google.com/document/d/1dzuv9x7mDtXYlc0ZZMP6qwvmsykWwzIpMQsdS-9sPGA/edit?usp=sharing) may also be useful.

**Comment by asvetlov** [comment]
It requires a separate github project, that's how cookiecutter works.
Better to make the project open-sourced from the very beginning.
