### ISSUE TITLE
Image parsing fallback

### ISSUE THREAD

**Issue by shagren** [neuromation/platform-client-python#971]
If you having invalid images like `image://shagren/:latest` which are incorrect but persist in you job history then latest `neuromation cli` will fail on `ps -a` command with error like:
```
  Invalid remote image 'dev.neu.ro/shagren/:latest': empty name or empty tag
```

Let's add some UnknownImage/UnparsableImage class for handling this case for `ps` / `status` commands.

**Comment by asvetlov** [comment]
Thanks for the report.
We should construct something like `Invalid Image Name` [here] (https://github.com/neuromation/platform-client-python/blob/master/neuromation/api/jobs.py#L363-L372) if `parse_image()` call raises exception.

**Comment by dalazx** [comment]
addressed by the referenced PR.
