### ISSUE TITLE
Implement mounting all available volumes

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#974]
similarly to `--volume=HOME` we might want to introduce another option: `--volume=ALL`.

it would mount all the storage URIs available to the user under the known root directory.

1. Expose an env var denoting the root;
2. Request `neuro acl list` for the storage scheme via API;
3. Define the volumes list with the appropriate R/W mode;

Some question:
How would `ALL` play with `HOME`?
How would `ALL` play with `--pass-config`?

**Comment by ayushkovskiy** [comment]
> How would ALL play with HOME?
k> How would ALL play with --pass-config?

for now, let's forbid both

**Comment by ayushkovskiy** [comment]
Blocked by: https://github.com/neuromation/platform-client-python/issues/975
