### ISSUE TITLE
Resource `storage://neuromation` is not public anymore?

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#975]
```
$ n run --detach -s cpu-small -n test --volume=HOME ubuntu "sleep 30m" 
ERROR: Not enough permissions ({"resources": [{"uri": "storage://neuromation", "action": "read"}]})
```

**Comment by ayushkovskiy** [comment]
- on dev, no neuromation resources are published.
- on staging, we have few public resources by neuromation:
```
image://neuromation/fastai read
image://neuromation/rsync read
storage://neuromation/public read
```

It seems that we should not mount `storage://neuromation` by default with `--volume=HOME` but at least mount `storage://neuromation/public` (still needs to be shared on dev).

**Comment by dalazx** [comment]
not sure `storage://neuromation` was even meant to be public, whereas `storage://neuromation/public` was.

**Comment by ayushkovskiy** [comment]
OK, I'll issue the PR that fixes `storage://neuromation` -> `storage://neuromation/public` when `--volume=HOME`

Also, I'll add the following permissions on `dev`:
```
$ n acl list --shared
image://neuromation/fastai read public
image://neuromation/rsync read public
storage://neuromation/public read public
```
