### ISSUE TITLE
Support `neuro acl` operations with job-name in job-URI

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#989]
Patch `parse_resource_for_sharing` to resolve `job://owner/job-name` -> `job://owner/job-ID` and then share it (see https://github.com/neuromation/platform-client-python/issues/968)

**Comment by dalazx** [comment]
URIs should not have names in them because names are not unique.

**Comment by ayushkovskiy** [comment]
> URIs should not have names in them because names are not unique.

why not? we have a defined algorithm of resolving job by job name, and by introducing job URIs we add the users ability to address other users' jobs, so job names are resolved to job IDs in the same way.

**Comment by ayushkovskiy** [comment]
note that job URIs like `job://{owner}/{job-name}` are faced only to the user: the job-name is resolved to job-ID on CLI-side, so the server always gets unambigous URIs.

**Comment by serhiy-storchaka** [comment]
You can now share job by name. https://github.com/neuromation/platform-api/issues/1221

It shares all past, running and future jobs with this name.
