### ISSUE TITLE
Cover `build_env()`

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#995]
Original concern: https://github.com/neuromation/platform-client-python/pull/980#discussion_r317589123

https://github.com/neuromation/platform-client-python/blob/1e36ca65a0456495bff37df52bd51e0a5263ffb0/neuromation/cli/job.py#L63-L77
not covered at all.

**Comment by asvetlov** [comment]
According to codecov.io it **is** covered
