### ISSUE TITLE
[Maybe] Forbid sharing root resource

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#997]
I think, we need to make `neuro acl` commands a bit more save and forbid sharing self user's root:
```
$ n share job: user read
>>> should be error
```

for all resources: `job`, `image`, `storage`

**Comment by dalazx** [comment]
as long as you `manage` it, why not?

I think this is a job of the future resource sharing micro service to enforce such rules.

**Comment by asvetlov** [comment]
agree with @dalazx 
If you really want to prevent something -- better to do it on the server side.
